version: '3'
services:
  jaeger-collector:
    image: registry.cn-beijing.aliyuncs.com/eviltomorrow/jaeger-collector:1.47
    container_name: jaeger-collector
    command:
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
      - "--collector.zipkin.host-port=:9411"
      - "--collector.otlp.enabled=false"
    environment:
      - SAMPLING_CONFIG_TYPE=adaptive
      - SPAN_STORAGE_TYPE=cassandra
    ports:
      - "14269:14269"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    restart: always
    depends_on:
      - cassandra-schema
    networks:
      - net-jaeger

  jaeger-query:
    image: registry.cn-beijing.aliyuncs.com/eviltomorrow/jaeger-query:1.47
    container_name: jaeger-query
    command:
      ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
    environment:
      - SPAN_STORAGE_TYPE=cassandra
      - SAMPLING_CONFIG_TYPE=adaptive
      - SAMPLING_STORAGE_TYPE=cassandra
    ports:
      - "16685:16685"
      - "16686:16686"
      - "16687"
    restart: always
    depends_on:
      - cassandra-schema
    networks:
      - net-jaeger

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.83.0
    container_name: otel-collector
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./conf/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-collector
    networks:
      - net-jaeger
      - net-king

  cassandra:
    image: registry.cn-beijing.aliyuncs.com/eviltomorrow/cassandra:4.1.3
    restart: on-failure
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - "./data/cassandra/db:/var/lib/cassandra"
      - "./data/cassandra/logs:/var/log/cassandra"
    networks:
      - net-jaeger

  cassandra-schema:
    image: registry.cn-beijing.aliyuncs.com/eviltomorrow/jaeger-cassandra-schema:1.47
    restart: on-failure
    container_name: cassandra-schema
    depends_on:
      - cassandra
    networks:
      - net-jaeger

  mongo:
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - LANG=zh_CN.UTF-8
    volumes:
      - $PWD/data/mongo/conf:/etc/mongo/
      - $PWD/data/mongo/db:/var/lib/mongo/
      - $PWD/data/mongo/logs:/var/log/mongo/
      - $PWD/data/mongo/init/init_mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo/
    command: ["--auth","--config","/etc/mongo/mongod.conf"]
    image: registry.cn-beijing.aliyuncs.com/eviltomorrow/mongo:6.0.6
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - net-king

  mysql:
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - $PWD/data/mysql/conf:/etc/mysql/conf.d/
      - $PWD/data/mysql/db:/var/lib/mysql/
      - $PWD/data/mysql/logs:/var/log/mysql/
      - $PWD/data/mysql/init:/docker-entrypoint-initdb.d/
      - /run/mysqld:/run/mysqld/
      - /usr/share/zoneinfo:/usr/share/zoneinfo/
      - /etc/localtime:/etc/localtime:ro
    image: registry.cn-beijing.aliyuncs.com/eviltomorrow/mysql:8.0.33
    container_name: mysql
    ports:
      - 3306:3306
    privileged: true
    networks:
      - net-king

  etcd:
    restart: always
    environment:               
      - ALLOW_NONE_AUTHENTICATION=yes                                   
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379          
      - ETCDCTL_API=3                                            
    volumes:
      - $PWD/data/etcd:/etcd-data/                       
      - /etc/localtime:/etc/localtime:ro
    image: registry.cn-beijing.aliyuncs.com/eviltomorrow/etcd:3.4.26
    container_name: etcd                
    ports:                   
      - "2379:2379"
      - "2380:2380"
    networks:
      - net-king

  king-collector:     
    restart: always                                    
    volumes:
      - $PWD/logs/king-collector:/app/var/log/                      
      - /etc/localtime:/etc/localtime:ro
    image: registry.cn-beijing.aliyuncs.com/eviltomorrow/king-collector
    container_name: king-collector                
    ports:                   
      - "5271:5271"
    depends_on:
      - etcd
      - mysql
      - mongo
    networks:
      - net-king

  king-email:   
    restart: always                                      
    volumes:
      - $PWD/logs/king-email:/app/var/log/                      
      - /etc/localtime:/etc/localtime:ro
      - $PWD/conf/king-email/etc/smtp.json:/app/etc/smtp.json
    image: registry.cn-beijing.aliyuncs.com/eviltomorrow/king-email
    container_name: king-email                
    ports:                   
      - "5273:5273"
    depends_on:
      - etcd
      - mysql
      - mongo
    networks:
      - net-king

  king-repository:   
    restart: always                                      
    volumes:
      - $PWD/logs/king-repository:/app/var/log/                       
      - /etc/localtime:/etc/localtime:ro
    image: registry.cn-beijing.aliyuncs.com/eviltomorrow/king-repository
    container_name: king-repository                
    ports:                   
      - "5272:5272"
    depends_on:
      - etcd
      - mysql
      - mongo
    networks:
      - net-king
      
networks:
  net-king:
    name: net-king
    driver: bridge
  net-jaeger:
    name: net-jaeger
    driver: bridge
