// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: email.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mail_ContentType int32

const (
	Mail_TEXT_HTML  Mail_ContentType = 0
	Mail_TEXT_PLAIN Mail_ContentType = 1
)

// Enum value maps for Mail_ContentType.
var (
	Mail_ContentType_name = map[int32]string{
		0: "TEXT_HTML",
		1: "TEXT_PLAIN",
	}
	Mail_ContentType_value = map[string]int32{
		"TEXT_HTML":  0,
		"TEXT_PLAIN": 1,
	}
)

func (x Mail_ContentType) Enum() *Mail_ContentType {
	p := new(Mail_ContentType)
	*p = x
	return p
}

func (x Mail_ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mail_ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_email_proto_enumTypes[0].Descriptor()
}

func (Mail_ContentType) Type() protoreflect.EnumType {
	return &file_email_proto_enumTypes[0]
}

func (x Mail_ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mail_ContentType.Descriptor instead.
func (Mail_ContentType) EnumDescriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{0, 0}
}

type Mail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            []*Contact             `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	Cc            []*Contact             `protobuf:"bytes,2,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc           []*Contact             `protobuf:"bytes,3,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	ContentType   Mail_ContentType       `protobuf:"varint,6,opt,name=content_type,json=contentType,proto3,enum=notification.Mail_ContentType" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mail) Reset() {
	*x = Mail{}
	mi := &file_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mail) ProtoMessage() {}

func (x *Mail) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mail.ProtoReflect.Descriptor instead.
func (*Mail) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{0}
}

func (x *Mail) GetTo() []*Contact {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Mail) GetCc() []*Contact {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *Mail) GetBcc() []*Contact {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *Mail) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Mail) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Mail) GetContentType() Mail_ContentType {
	if x != nil {
		return x.ContentType
	}
	return Mail_TEXT_HTML
}

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{1}
}

func (x *Contact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contact) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_email_proto protoreflect.FileDescriptor

const file_email_proto_rawDesc = "" +
	"\n" +
	"\vemail.proto\x12\fnotification\x1a\x1egoogle/protobuf/wrappers.proto\"\x9c\x02\n" +
	"\x04Mail\x12%\n" +
	"\x02to\x18\x01 \x03(\v2\x15.notification.ContactR\x02to\x12%\n" +
	"\x02cc\x18\x02 \x03(\v2\x15.notification.ContactR\x02cc\x12'\n" +
	"\x03bcc\x18\x03 \x03(\v2\x15.notification.ContactR\x03bcc\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12A\n" +
	"\fcontent_type\x18\x06 \x01(\x0e2\x1e.notification.Mail.ContentTypeR\vcontentType\",\n" +
	"\vContentType\x12\r\n" +
	"\tTEXT_HTML\x10\x00\x12\x0e\n" +
	"\n" +
	"TEXT_PLAIN\x10\x01\"7\n" +
	"\aContact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress2C\n" +
	"\x05Email\x12:\n" +
	"\x04Send\x12\x12.notification.Mail\x1a\x1c.google.protobuf.StringValue\"\x00B\aZ\x05./;pbb\x06proto3"

var (
	file_email_proto_rawDescOnce sync.Once
	file_email_proto_rawDescData []byte
)

func file_email_proto_rawDescGZIP() []byte {
	file_email_proto_rawDescOnce.Do(func() {
		file_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_email_proto_rawDesc), len(file_email_proto_rawDesc)))
	})
	return file_email_proto_rawDescData
}

var file_email_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_email_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_email_proto_goTypes = []any{
	(Mail_ContentType)(0),          // 0: notification.Mail.ContentType
	(*Mail)(nil),                   // 1: notification.Mail
	(*Contact)(nil),                // 2: notification.Contact
	(*wrapperspb.StringValue)(nil), // 3: google.protobuf.StringValue
}
var file_email_proto_depIdxs = []int32{
	2, // 0: notification.Mail.to:type_name -> notification.Contact
	2, // 1: notification.Mail.cc:type_name -> notification.Contact
	2, // 2: notification.Mail.bcc:type_name -> notification.Contact
	0, // 3: notification.Mail.content_type:type_name -> notification.Mail.ContentType
	1, // 4: notification.Email.Send:input_type -> notification.Mail
	3, // 5: notification.Email.Send:output_type -> google.protobuf.StringValue
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_email_proto_init() }
func file_email_proto_init() {
	if File_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_email_proto_rawDesc), len(file_email_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_email_proto_goTypes,
		DependencyIndexes: file_email_proto_depIdxs,
		EnumInfos:         file_email_proto_enumTypes,
		MessageInfos:      file_email_proto_msgTypes,
	}.Build()
	File_email_proto = out.File
	file_email_proto_goTypes = nil
	file_email_proto_depIdxs = nil
}
