// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: ntfy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Priority      int64                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Attach        string                 `protobuf:"bytes,5,opt,name=attach,proto3" json:"attach,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_ntfy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_ntfy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_ntfy_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Msg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Msg) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Msg) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Msg) GetAttach() string {
	if x != nil {
		return x.Attach
	}
	return ""
}

func (x *Msg) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_ntfy_proto protoreflect.FileDescriptor

const file_ntfy_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"ntfy.proto\x12\fnotification\x1a\x1egoogle/protobuf/wrappers.proto\"\x93\x01\n" +
	"\x03Msg\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x03R\bpriority\x12\x16\n" +
	"\x06attach\x18\x05 \x01(\tR\x06attach\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags2A\n" +
	"\x04Ntfy\x129\n" +
	"\x04Send\x12\x11.notification.Msg\x1a\x1c.google.protobuf.StringValue\"\x00B\aZ\x05./;pbb\x06proto3"

var (
	file_ntfy_proto_rawDescOnce sync.Once
	file_ntfy_proto_rawDescData []byte
)

func file_ntfy_proto_rawDescGZIP() []byte {
	file_ntfy_proto_rawDescOnce.Do(func() {
		file_ntfy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ntfy_proto_rawDesc), len(file_ntfy_proto_rawDesc)))
	})
	return file_ntfy_proto_rawDescData
}

var file_ntfy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ntfy_proto_goTypes = []any{
	(*Msg)(nil),                    // 0: notification.Msg
	(*wrapperspb.StringValue)(nil), // 1: google.protobuf.StringValue
}
var file_ntfy_proto_depIdxs = []int32{
	0, // 0: notification.Ntfy.Send:input_type -> notification.Msg
	1, // 1: notification.Ntfy.Send:output_type -> google.protobuf.StringValue
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ntfy_proto_init() }
func file_ntfy_proto_init() {
	if File_ntfy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ntfy_proto_rawDesc), len(file_ntfy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ntfy_proto_goTypes,
		DependencyIndexes: file_ntfy_proto_depIdxs,
		MessageInfos:      file_ntfy_proto_msgTypes,
	}.Build()
	File_ntfy_proto = out.File
	file_ntfy_proto_goTypes = nil
	file_ntfy_proto_depIdxs = nil
}
