[global]
## 过户费
transfer_fee_ratio = "0.001%"
transfer_fee_pay_method = ["buy", "sell"]
## 佣金
commission_ratio = "0.018%"
commission_pay_method = ["buy", "sell"]
## 印花税
stamp_tax_ratio = "0.05%"
stamp_tax_pay_method = ["sell"]

[grpc]
access_ip = ""
bind_ip = "0.0.0.0"
bind_port = 50005

[etcd]
endpoints = ["etcd:2379"]

[log]
level = "info"

[otel]
dsn = "otel-collector:4317"

[mysql]
dsn = "admin:admin123@tcp(mysql:3306)/king_account?charset=utf8mb4&parseTime=true&loc=Local"
min_open = 3
max_open = 10
