[global]
	## 过户费
	transfer-fee-ratio = "0.001%"
	transfer-fee-pay-method = ["buy", "sell"]
	## 佣金
	commission-ratio = "0.018%"
	commission-pay-method = ["buy", "sell"]
	## 印花税
	stamp-tax-ratio = "0.05%"
	stamp-tax-pay-method = ["sell"]

[server]
	host = "0.0.0.0"
	port = 5275

[etcd]
	endpoints = [
		"etcd:2379",
	]

[otel]
    dsn = "otel-collector:4317"
	
[mysql]
	dsn = "admin:admin123@tcp(mysql:3306)/king_account?charset=utf8mb4&parseTime=true&loc=Local"
	min-open = 3
	max-open = 10

