// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: finder.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stock) Reset() {
	*x = Stock{}
	mi := &file_finder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_finder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_finder_proto_rawDescGZIP(), []int{0}
}

func (x *Stock) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Stock) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_finder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_finder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_finder_proto_rawDescGZIP(), []int{1}
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type Chance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         *Stock                 `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	Model         *Model                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chance) Reset() {
	*x = Chance{}
	mi := &file_finder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chance) ProtoMessage() {}

func (x *Chance) ProtoReflect() protoreflect.Message {
	mi := &file_finder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chance.ProtoReflect.Descriptor instead.
func (*Chance) Descriptor() ([]byte, []int) {
	return file_finder_proto_rawDescGZIP(), []int{2}
}

func (x *Chance) GetStock() *Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

func (x *Chance) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

type Chances struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chances       []*Chance              `protobuf:"bytes,1,rep,name=chances,proto3" json:"chances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chances) Reset() {
	*x = Chances{}
	mi := &file_finder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chances) ProtoMessage() {}

func (x *Chances) ProtoReflect() protoreflect.Message {
	mi := &file_finder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chances.ProtoReflect.Descriptor instead.
func (*Chances) Descriptor() ([]byte, []int) {
	return file_finder_proto_rawDescGZIP(), []int{3}
}

func (x *Chances) GetChances() []*Chance {
	if x != nil {
		return x.Chances
	}
	return nil
}

var File_finder_proto protoreflect.FileDescriptor

const file_finder_proto_rawDesc = "" +
	"\n" +
	"\ffinder.proto\x12\x05brain\x1a\x1egoogle/protobuf/wrappers.proto\"/\n" +
	"\x05Stock\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"/\n" +
	"\x05Model\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\"P\n" +
	"\x06Chance\x12\"\n" +
	"\x05stock\x18\x01 \x01(\v2\f.brain.StockR\x05stock\x12\"\n" +
	"\x05model\x18\x02 \x01(\v2\f.brain.ModelR\x05model\"2\n" +
	"\aChances\x12'\n" +
	"\achances\x18\x01 \x03(\v2\r.brain.ChanceR\achances2L\n" +
	"\x06Finder\x12B\n" +
	"\x12FindPossibleChance\x12\x1c.google.protobuf.StringValue\x1a\x0e.brain.ChancesB\aZ\x05./;pbb\x06proto3"

var (
	file_finder_proto_rawDescOnce sync.Once
	file_finder_proto_rawDescData []byte
)

func file_finder_proto_rawDescGZIP() []byte {
	file_finder_proto_rawDescOnce.Do(func() {
		file_finder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finder_proto_rawDesc), len(file_finder_proto_rawDesc)))
	})
	return file_finder_proto_rawDescData
}

var file_finder_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_finder_proto_goTypes = []any{
	(*Stock)(nil),                  // 0: brain.Stock
	(*Model)(nil),                  // 1: brain.Model
	(*Chance)(nil),                 // 2: brain.Chance
	(*Chances)(nil),                // 3: brain.Chances
	(*wrapperspb.StringValue)(nil), // 4: google.protobuf.StringValue
}
var file_finder_proto_depIdxs = []int32{
	0, // 0: brain.Chance.stock:type_name -> brain.Stock
	1, // 1: brain.Chance.model:type_name -> brain.Model
	2, // 2: brain.Chances.chances:type_name -> brain.Chance
	4, // 3: brain.Finder.FindPossibleChance:input_type -> google.protobuf.StringValue
	3, // 4: brain.Finder.FindPossibleChance:output_type -> brain.Chances
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_finder_proto_init() }
func file_finder_proto_init() {
	if File_finder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finder_proto_rawDesc), len(file_finder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finder_proto_goTypes,
		DependencyIndexes: file_finder_proto_depIdxs,
		MessageInfos:      file_finder_proto_msgTypes,
	}.Build()
	File_finder_proto = out.File
	file_finder_proto_goTypes = nil
	file_finder_proto_depIdxs = nil
}
