// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.0
// source: finder.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Finder_DiscoverPossibleChance_FullMethodName  = "/brain.Finder/DiscoverPossibleChance"
	Finder_CreateBuyPlan_FullMethodName           = "/brain.Finder/CreateBuyPlan"
	Finder_FollowReturnWithBuyPlan_FullMethodName = "/brain.Finder/FollowReturnWithBuyPlan"
)

// FinderClient is the client API for Finder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinderClient interface {
	DiscoverPossibleChance(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (Finder_DiscoverPossibleChanceClient, error)
	CreateBuyPlan(ctx context.Context, in *PossibleChance, opts ...grpc.CallOption) (*BuyPlan, error)
	FollowReturnWithBuyPlan(ctx context.Context, in *BuyPlan, opts ...grpc.CallOption) (*PositionPlan, error)
}

type finderClient struct {
	cc grpc.ClientConnInterface
}

func NewFinderClient(cc grpc.ClientConnInterface) FinderClient {
	return &finderClient{cc}
}

func (c *finderClient) DiscoverPossibleChance(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (Finder_DiscoverPossibleChanceClient, error) {
	stream, err := c.cc.NewStream(ctx, &Finder_ServiceDesc.Streams[0], Finder_DiscoverPossibleChance_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &finderDiscoverPossibleChanceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Finder_DiscoverPossibleChanceClient interface {
	Recv() (*PossibleChance, error)
	grpc.ClientStream
}

type finderDiscoverPossibleChanceClient struct {
	grpc.ClientStream
}

func (x *finderDiscoverPossibleChanceClient) Recv() (*PossibleChance, error) {
	m := new(PossibleChance)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *finderClient) CreateBuyPlan(ctx context.Context, in *PossibleChance, opts ...grpc.CallOption) (*BuyPlan, error) {
	out := new(BuyPlan)
	err := c.cc.Invoke(ctx, Finder_CreateBuyPlan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finderClient) FollowReturnWithBuyPlan(ctx context.Context, in *BuyPlan, opts ...grpc.CallOption) (*PositionPlan, error) {
	out := new(PositionPlan)
	err := c.cc.Invoke(ctx, Finder_FollowReturnWithBuyPlan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinderServer is the server API for Finder service.
// All implementations must embed UnimplementedFinderServer
// for forward compatibility
type FinderServer interface {
	DiscoverPossibleChance(*wrapperspb.StringValue, Finder_DiscoverPossibleChanceServer) error
	CreateBuyPlan(context.Context, *PossibleChance) (*BuyPlan, error)
	FollowReturnWithBuyPlan(context.Context, *BuyPlan) (*PositionPlan, error)
	mustEmbedUnimplementedFinderServer()
}

// UnimplementedFinderServer must be embedded to have forward compatible implementations.
type UnimplementedFinderServer struct {
}

func (UnimplementedFinderServer) DiscoverPossibleChance(*wrapperspb.StringValue, Finder_DiscoverPossibleChanceServer) error {
	return status.Errorf(codes.Unimplemented, "method DiscoverPossibleChance not implemented")
}
func (UnimplementedFinderServer) CreateBuyPlan(context.Context, *PossibleChance) (*BuyPlan, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBuyPlan not implemented")
}
func (UnimplementedFinderServer) FollowReturnWithBuyPlan(context.Context, *BuyPlan) (*PositionPlan, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowReturnWithBuyPlan not implemented")
}
func (UnimplementedFinderServer) mustEmbedUnimplementedFinderServer() {}

// UnsafeFinderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinderServer will
// result in compilation errors.
type UnsafeFinderServer interface {
	mustEmbedUnimplementedFinderServer()
}

func RegisterFinderServer(s grpc.ServiceRegistrar, srv FinderServer) {
	s.RegisterService(&Finder_ServiceDesc, srv)
}

func _Finder_DiscoverPossibleChance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(wrapperspb.StringValue)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FinderServer).DiscoverPossibleChance(m, &finderDiscoverPossibleChanceServer{stream})
}

type Finder_DiscoverPossibleChanceServer interface {
	Send(*PossibleChance) error
	grpc.ServerStream
}

type finderDiscoverPossibleChanceServer struct {
	grpc.ServerStream
}

func (x *finderDiscoverPossibleChanceServer) Send(m *PossibleChance) error {
	return x.ServerStream.SendMsg(m)
}

func _Finder_CreateBuyPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PossibleChance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinderServer).CreateBuyPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finder_CreateBuyPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinderServer).CreateBuyPlan(ctx, req.(*PossibleChance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finder_FollowReturnWithBuyPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyPlan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinderServer).FollowReturnWithBuyPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finder_FollowReturnWithBuyPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinderServer).FollowReturnWithBuyPlan(ctx, req.(*BuyPlan))
	}
	return interceptor(ctx, in, info, handler)
}

// Finder_ServiceDesc is the grpc.ServiceDesc for Finder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Finder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brain.Finder",
	HandlerType: (*FinderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBuyPlan",
			Handler:    _Finder_CreateBuyPlan_Handler,
		},
		{
			MethodName: "FollowReturnWithBuyPlan",
			Handler:    _Finder_FollowReturnWithBuyPlan_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DiscoverPossibleChance",
			Handler:       _Finder_DiscoverPossibleChance_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "finder.proto",
}
