// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0-devel
// 	protoc        v4.23.2
// source: finder.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PossibleChance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date  string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Stock *Stock `protobuf:"bytes,2,opt,name=stock,proto3" json:"stock,omitempty"`
	Model *Model `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *PossibleChance) Reset() {
	*x = PossibleChance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PossibleChance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PossibleChance) ProtoMessage() {}

func (x *PossibleChance) ProtoReflect() protoreflect.Message {
	mi := &file_finder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PossibleChance.ProtoReflect.Descriptor instead.
func (*PossibleChance) Descriptor() ([]byte, []int) {
	return file_finder_proto_rawDescGZIP(), []int{0}
}

func (x *PossibleChance) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *PossibleChance) GetStock() *Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

func (x *PossibleChance) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

type Stock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Stock) Reset() {
	*x = Stock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_finder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_finder_proto_rawDescGZIP(), []int{1}
}

func (x *Stock) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Stock) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Model struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *Model) Reset() {
	*x = Model{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_finder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_finder_proto_rawDescGZIP(), []int{2}
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type BuyPlan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BuyPlan) Reset() {
	*x = BuyPlan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyPlan) ProtoMessage() {}

func (x *BuyPlan) ProtoReflect() protoreflect.Message {
	mi := &file_finder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyPlan.ProtoReflect.Descriptor instead.
func (*BuyPlan) Descriptor() ([]byte, []int) {
	return file_finder_proto_rawDescGZIP(), []int{3}
}

type PositionPlan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PositionPlan) Reset() {
	*x = PositionPlan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finder_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionPlan) ProtoMessage() {}

func (x *PositionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_finder_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionPlan.ProtoReflect.Descriptor instead.
func (*PositionPlan) Descriptor() ([]byte, []int) {
	return file_finder_proto_rawDescGZIP(), []int{4}
}

var File_finder_proto protoreflect.FileDescriptor

var file_finder_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x62, 0x72, 0x61, 0x69, 0x6e, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x0e, 0x50, 0x6f, 0x73, 0x73, 0x69, 0x62, 0x6c,
	0x65, 0x43, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x72, 0x61,
	0x69, 0x6e, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12,
	0x22, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x22, 0x2f, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x22, 0x09, 0x0a, 0x07, 0x42, 0x75, 0x79, 0x50, 0x6c, 0x61, 0x6e,
	0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x6e,
	0x32, 0xd7, 0x01, 0x0a, 0x06, 0x46, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x51, 0x0a, 0x16, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x1a, 0x15, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x73, 0x73,
	0x69, 0x62, 0x6c, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x38,
	0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x12,
	0x15, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x73, 0x73, 0x69, 0x62, 0x6c, 0x65,
	0x43, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x0e, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x42,
	0x75, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x17, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x42, 0x75, 0x79, 0x50,
	0x6c, 0x61, 0x6e, 0x12, 0x0e, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x42, 0x75, 0x79, 0x50,
	0x6c, 0x61, 0x6e, 0x1a, 0x13, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x6e, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_finder_proto_rawDescOnce sync.Once
	file_finder_proto_rawDescData = file_finder_proto_rawDesc
)

func file_finder_proto_rawDescGZIP() []byte {
	file_finder_proto_rawDescOnce.Do(func() {
		file_finder_proto_rawDescData = protoimpl.X.CompressGZIP(file_finder_proto_rawDescData)
	})
	return file_finder_proto_rawDescData
}

var file_finder_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_finder_proto_goTypes = []interface{}{
	(*PossibleChance)(nil),         // 0: brain.PossibleChance
	(*Stock)(nil),                  // 1: brain.Stock
	(*Model)(nil),                  // 2: brain.Model
	(*BuyPlan)(nil),                // 3: brain.BuyPlan
	(*PositionPlan)(nil),           // 4: brain.PositionPlan
	(*wrapperspb.StringValue)(nil), // 5: google.protobuf.StringValue
}
var file_finder_proto_depIdxs = []int32{
	1, // 0: brain.PossibleChance.stock:type_name -> brain.Stock
	2, // 1: brain.PossibleChance.model:type_name -> brain.Model
	5, // 2: brain.Finder.DiscoverPossibleChance:input_type -> google.protobuf.StringValue
	0, // 3: brain.Finder.CreateBuyPlan:input_type -> brain.PossibleChance
	3, // 4: brain.Finder.FollowReturnWithBuyPlan:input_type -> brain.BuyPlan
	0, // 5: brain.Finder.DiscoverPossibleChance:output_type -> brain.PossibleChance
	3, // 6: brain.Finder.CreateBuyPlan:output_type -> brain.BuyPlan
	4, // 7: brain.Finder.FollowReturnWithBuyPlan:output_type -> brain.PositionPlan
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_finder_proto_init() }
func file_finder_proto_init() {
	if File_finder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_finder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PossibleChance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Model); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyPlan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finder_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionPlan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_finder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finder_proto_goTypes,
		DependencyIndexes: file_finder_proto_depIdxs,
		MessageInfos:      file_finder_proto_msgTypes,
	}.Build()
	File_finder_proto = out.File
	file_finder_proto_rawDesc = nil
	file_finder_proto_goTypes = nil
	file_finder_proto_depIdxs = nil
}
