// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: collector.proto

package pb

import (
	entity "github.com/eviltomorrow/king/lib/grpc/pb/entity"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CrawlMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Ignore        int64                  `protobuf:"varint,2,opt,name=ignore,proto3" json:"ignore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlMetadataResponse) Reset() {
	*x = CrawlMetadataResponse{}
	mi := &file_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlMetadataResponse) ProtoMessage() {}

func (x *CrawlMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlMetadataResponse.ProtoReflect.Descriptor instead.
func (*CrawlMetadataResponse) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{0}
}

func (x *CrawlMetadataResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CrawlMetadataResponse) GetIgnore() int64 {
	if x != nil {
		return x.Ignore
	}
	return 0
}

var File_collector_proto protoreflect.FileDescriptor

const file_collector_proto_rawDesc = "" +
	"\n" +
	"\x0fcollector.proto\x12\tcollector\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19lib/entity/metadata.proto\"E\n" +
	"\x15CrawlMetadataResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x16\n" +
	"\x06ignore\x18\x02 \x01(\x03R\x06ignore2\xed\x01\n" +
	"\tCollector\x12L\n" +
	"\x12CrawlMetadataAsync\x12\x1c.google.protobuf.StringValue\x1a\x16.google.protobuf.Empty\"\x00\x12U\n" +
	"\x11CrawlMetadataSync\x12\x1c.google.protobuf.StringValue\x1a .collector.CrawlMetadataResponse\"\x00\x12;\n" +
	"\fPullMetadata\x12\x1c.google.protobuf.StringValue\x1a\t.Metadata\"\x000\x01B\aZ\x05./;pbb\x06proto3"

var (
	file_collector_proto_rawDescOnce sync.Once
	file_collector_proto_rawDescData []byte
)

func file_collector_proto_rawDescGZIP() []byte {
	file_collector_proto_rawDescOnce.Do(func() {
		file_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collector_proto_rawDesc), len(file_collector_proto_rawDesc)))
	})
	return file_collector_proto_rawDescData
}

var file_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_collector_proto_goTypes = []any{
	(*CrawlMetadataResponse)(nil),  // 0: collector.CrawlMetadataResponse
	(*wrapperspb.StringValue)(nil), // 1: google.protobuf.StringValue
	(*emptypb.Empty)(nil),          // 2: google.protobuf.Empty
	(*entity.Metadata)(nil),        // 3: Metadata
}
var file_collector_proto_depIdxs = []int32{
	1, // 0: collector.Collector.CrawlMetadataAsync:input_type -> google.protobuf.StringValue
	1, // 1: collector.Collector.CrawlMetadataSync:input_type -> google.protobuf.StringValue
	1, // 2: collector.Collector.PullMetadata:input_type -> google.protobuf.StringValue
	2, // 3: collector.Collector.CrawlMetadataAsync:output_type -> google.protobuf.Empty
	0, // 4: collector.Collector.CrawlMetadataSync:output_type -> collector.CrawlMetadataResponse
	3, // 5: collector.Collector.PullMetadata:output_type -> Metadata
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_collector_proto_init() }
func file_collector_proto_init() {
	if File_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collector_proto_rawDesc), len(file_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collector_proto_goTypes,
		DependencyIndexes: file_collector_proto_depIdxs,
		MessageInfos:      file_collector_proto_msgTypes,
	}.Build()
	File_collector_proto = out.File
	file_collector_proto_goTypes = nil
	file_collector_proto_depIdxs = nil
}
