// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.2
// source: collector.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Collector_CrawlMetadata_FullMethodName = "/collector.Collector/CrawlMetadata"
	Collector_FetchMetadata_FullMethodName = "/collector.Collector/FetchMetadata"
)

// CollectorClient is the client API for Collector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectorClient interface {
	// Crawl last metadata with specify source(sina, net126)
	CrawlMetadata(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*Counter, error)
	// Fetch metadata to cloud repository
	FetchMetadata(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (Collector_FetchMetadataClient, error)
}

type collectorClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorClient(cc grpc.ClientConnInterface) CollectorClient {
	return &collectorClient{cc}
}

func (c *collectorClient) CrawlMetadata(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*Counter, error) {
	out := new(Counter)
	err := c.cc.Invoke(ctx, Collector_CrawlMetadata_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorClient) FetchMetadata(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (Collector_FetchMetadataClient, error) {
	stream, err := c.cc.NewStream(ctx, &Collector_ServiceDesc.Streams[0], Collector_FetchMetadata_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &collectorFetchMetadataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Collector_FetchMetadataClient interface {
	Recv() (*Metadata, error)
	grpc.ClientStream
}

type collectorFetchMetadataClient struct {
	grpc.ClientStream
}

func (x *collectorFetchMetadataClient) Recv() (*Metadata, error) {
	m := new(Metadata)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CollectorServer is the server API for Collector service.
// All implementations must embed UnimplementedCollectorServer
// for forward compatibility
type CollectorServer interface {
	// Crawl last metadata with specify source(sina, net126)
	CrawlMetadata(context.Context, *wrapperspb.StringValue) (*Counter, error)
	// Fetch metadata to cloud repository
	FetchMetadata(*wrapperspb.StringValue, Collector_FetchMetadataServer) error
	mustEmbedUnimplementedCollectorServer()
}

// UnimplementedCollectorServer must be embedded to have forward compatible implementations.
type UnimplementedCollectorServer struct {
}

func (UnimplementedCollectorServer) CrawlMetadata(context.Context, *wrapperspb.StringValue) (*Counter, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrawlMetadata not implemented")
}
func (UnimplementedCollectorServer) FetchMetadata(*wrapperspb.StringValue, Collector_FetchMetadataServer) error {
	return status.Errorf(codes.Unimplemented, "method FetchMetadata not implemented")
}
func (UnimplementedCollectorServer) mustEmbedUnimplementedCollectorServer() {}

// UnsafeCollectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectorServer will
// result in compilation errors.
type UnsafeCollectorServer interface {
	mustEmbedUnimplementedCollectorServer()
}

func RegisterCollectorServer(s grpc.ServiceRegistrar, srv CollectorServer) {
	s.RegisterService(&Collector_ServiceDesc, srv)
}

func _Collector_CrawlMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServer).CrawlMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collector_CrawlMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServer).CrawlMetadata(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collector_FetchMetadata_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(wrapperspb.StringValue)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CollectorServer).FetchMetadata(m, &collectorFetchMetadataServer{stream})
}

type Collector_FetchMetadataServer interface {
	Send(*Metadata) error
	grpc.ServerStream
}

type collectorFetchMetadataServer struct {
	grpc.ServerStream
}

func (x *collectorFetchMetadataServer) Send(m *Metadata) error {
	return x.ServerStream.SendMsg(m)
}

// Collector_ServiceDesc is the grpc.ServiceDesc for Collector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Collector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "collector.Collector",
	HandlerType: (*CollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrawlMetadata",
			Handler:    _Collector_CrawlMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchMetadata",
			Handler:       _Collector_FetchMetadata_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "collector.proto",
}
