// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: lib/protobuf/metadata.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source          string  `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Code            string  `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name            string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Open            float64 `protobuf:"fixed64,4,opt,name=open,proto3" json:"open,omitempty"`
	YesterdayClosed float64 `protobuf:"fixed64,5,opt,name=yesterday_closed,json=yesterdayClosed,proto3" json:"yesterday_closed,omitempty"`
	Latest          float64 `protobuf:"fixed64,6,opt,name=latest,proto3" json:"latest,omitempty"`
	High            float64 `protobuf:"fixed64,7,opt,name=high,proto3" json:"high,omitempty"`
	Low             float64 `protobuf:"fixed64,8,opt,name=low,proto3" json:"low,omitempty"`
	Volume          uint64  `protobuf:"varint,9,opt,name=volume,proto3" json:"volume,omitempty"`
	Account         float64 `protobuf:"fixed64,10,opt,name=account,proto3" json:"account,omitempty"`
	Date            string  `protobuf:"bytes,11,opt,name=date,proto3" json:"date,omitempty"`
	Time            string  `protobuf:"bytes,12,opt,name=time,proto3" json:"time,omitempty"`
	Suspend         string  `protobuf:"bytes,13,opt,name=suspend,proto3" json:"suspend,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_lib_protobuf_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_lib_protobuf_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_lib_protobuf_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Metadata) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Metadata) GetYesterdayClosed() float64 {
	if x != nil {
		return x.YesterdayClosed
	}
	return 0
}

func (x *Metadata) GetLatest() float64 {
	if x != nil {
		return x.Latest
	}
	return 0
}

func (x *Metadata) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Metadata) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Metadata) GetVolume() uint64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Metadata) GetAccount() float64 {
	if x != nil {
		return x.Account
	}
	return 0
}

func (x *Metadata) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Metadata) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Metadata) GetSuspend() string {
	if x != nil {
		return x.Suspend
	}
	return ""
}

var File_lib_protobuf_metadata_proto protoreflect.FileDescriptor

var file_lib_protobuf_metadata_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb, 0x02,
	0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70,
	0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x29,
	0x0a, 0x10, 0x79, 0x65, 0x73, 0x74, 0x65, 0x72, 0x64, 0x61, 0x79, 0x5f, 0x63, 0x6c, 0x6f, 0x73,
	0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0f, 0x79, 0x65, 0x73, 0x74, 0x65, 0x72,
	0x64, 0x61, 0x79, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x6c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lib_protobuf_metadata_proto_rawDescOnce sync.Once
	file_lib_protobuf_metadata_proto_rawDescData = file_lib_protobuf_metadata_proto_rawDesc
)

func file_lib_protobuf_metadata_proto_rawDescGZIP() []byte {
	file_lib_protobuf_metadata_proto_rawDescOnce.Do(func() {
		file_lib_protobuf_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_lib_protobuf_metadata_proto_rawDescData)
	})
	return file_lib_protobuf_metadata_proto_rawDescData
}

var file_lib_protobuf_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_lib_protobuf_metadata_proto_goTypes = []any{
	(*Metadata)(nil), // 0: Metadata
}
var file_lib_protobuf_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lib_protobuf_metadata_proto_init() }
func file_lib_protobuf_metadata_proto_init() {
	if File_lib_protobuf_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lib_protobuf_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lib_protobuf_metadata_proto_goTypes,
		DependencyIndexes: file_lib_protobuf_metadata_proto_depIdxs,
		MessageInfos:      file_lib_protobuf_metadata_proto_msgTypes,
	}.Build()
	File_lib_protobuf_metadata_proto = out.File
	file_lib_protobuf_metadata_proto_rawDesc = nil
	file_lib_protobuf_metadata_proto_goTypes = nil
	file_lib_protobuf_metadata_proto_depIdxs = nil
}
