{
 "title": "Logging King",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": {}
   },
   {
    "name": "type",
    "label": "type",
    "query": {}
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "info" }
  ]
 },
 "panels": [
  {
   "title": "日志总条数",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"$app\", type=~\"$type\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "日志总条数:  $searchable_pattern 级别",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"$app\", type=~\"$type\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "实时日志",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{app=\"$app\", type=~\"$type\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "日志总量卡片",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({type=\"$type\"})[$__interval])) by (app)"
    }
   ]
  },
  {
   "title": "日志匹配: \"$searchable_pattern\" 概览",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"$app\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (type)"
    }
   ]
  },
  {
   "title": "日志百分占比： \"$searchable_pattern\" 级别",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"$app\", type=~\"$type\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({app=\"$app\", type=~\"$type\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" historical",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({type=\"$type\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (app)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Rate per APP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(({type=\"$type\"} |~ \"(?i)$searchable_pattern\")[30s])) by (app)"
    }
   ]
  }
 ]
}