{
 "title": "Logging King",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": {}
   },
   {
    "name": "type",
    "label": "type",
    "query": {}
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "日志总条数",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=~\".+\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "日志条数: [app=\"$app\", type=\"$type\", search=\"$searchable_pattern\"]",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"$app\", type=~\"$type\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "实时日志:[app=\"$app\", type=\"$type\", search=\"$searchable_pattern\"]",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{app=\"$app\", type=~\"$type\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  },
  {
   "title": "日志卡片[type=\"$type\"]",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({type=\"$type\"})[$__interval])) by (app)"
    }
   ]
  },
  {
   "title": "日志占比:[app=\"$app\",search=\"$searchable_pattern\"]",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"$app\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (type)"
    }
   ]
  },
  {
   "title": "直方图:[type=\"$type\", search=\"$searchable_pattern\"]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(count_over_time(({type=\"$type\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (app)"
    }
   ]
  },
  {
   "title": "速率图：[type=\"$type\", search=\"$searchable_pattern\"]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(({type=\"$type\"} |~ \"(?i)$searchable_pattern\")[30s])) by (app)"
    }
   ]
  }
 ]
}