// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: storage.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Storage_ArchiveMetadata_FullMethodName = "/storage.Storage/ArchiveMetadata"
	Storage_GetStockOne_FullMethodName     = "/storage.Storage/GetStockOne"
	Storage_GetStockAll_FullMethodName     = "/storage.Storage/GetStockAll"
	Storage_GetQuoteLatest_FullMethodName  = "/storage.Storage/GetQuoteLatest"
)

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageClient interface {
	ArchiveMetadata(ctx context.Context, opts ...grpc.CallOption) (Storage_ArchiveMetadataClient, error)
	GetStockOne(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*Stock, error)
	GetStockAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Storage_GetStockAllClient, error)
	GetQuoteLatest(ctx context.Context, in *GetQuoteLatestRequest, opts ...grpc.CallOption) (Storage_GetQuoteLatestClient, error)
}

type storageClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageClient(cc grpc.ClientConnInterface) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) ArchiveMetadata(ctx context.Context, opts ...grpc.CallOption) (Storage_ArchiveMetadataClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Storage_ServiceDesc.Streams[0], Storage_ArchiveMetadata_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &storageArchiveMetadataClient{ClientStream: stream}
	return x, nil
}

type Storage_ArchiveMetadataClient interface {
	Send(*Metadata) error
	CloseAndRecv() (*ArchiveResponse, error)
	grpc.ClientStream
}

type storageArchiveMetadataClient struct {
	grpc.ClientStream
}

func (x *storageArchiveMetadataClient) Send(m *Metadata) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storageArchiveMetadataClient) CloseAndRecv() (*ArchiveResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ArchiveResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageClient) GetStockOne(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*Stock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Stock)
	err := c.cc.Invoke(ctx, Storage_GetStockOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetStockAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Storage_GetStockAllClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Storage_ServiceDesc.Streams[1], Storage_GetStockAll_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &storageGetStockAllClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Storage_GetStockAllClient interface {
	Recv() (*Stock, error)
	grpc.ClientStream
}

type storageGetStockAllClient struct {
	grpc.ClientStream
}

func (x *storageGetStockAllClient) Recv() (*Stock, error) {
	m := new(Stock)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageClient) GetQuoteLatest(ctx context.Context, in *GetQuoteLatestRequest, opts ...grpc.CallOption) (Storage_GetQuoteLatestClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Storage_ServiceDesc.Streams[2], Storage_GetQuoteLatest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &storageGetQuoteLatestClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Storage_GetQuoteLatestClient interface {
	Recv() (*Quote, error)
	grpc.ClientStream
}

type storageGetQuoteLatestClient struct {
	grpc.ClientStream
}

func (x *storageGetQuoteLatestClient) Recv() (*Quote, error) {
	m := new(Quote)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StorageServer is the server API for Storage service.
// All implementations must embed UnimplementedStorageServer
// for forward compatibility
type StorageServer interface {
	ArchiveMetadata(Storage_ArchiveMetadataServer) error
	GetStockOne(context.Context, *wrapperspb.StringValue) (*Stock, error)
	GetStockAll(*emptypb.Empty, Storage_GetStockAllServer) error
	GetQuoteLatest(*GetQuoteLatestRequest, Storage_GetQuoteLatestServer) error
	mustEmbedUnimplementedStorageServer()
}

// UnimplementedStorageServer must be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (UnimplementedStorageServer) ArchiveMetadata(Storage_ArchiveMetadataServer) error {
	return status.Errorf(codes.Unimplemented, "method ArchiveMetadata not implemented")
}
func (UnimplementedStorageServer) GetStockOne(context.Context, *wrapperspb.StringValue) (*Stock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStockOne not implemented")
}
func (UnimplementedStorageServer) GetStockAll(*emptypb.Empty, Storage_GetStockAllServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStockAll not implemented")
}
func (UnimplementedStorageServer) GetQuoteLatest(*GetQuoteLatestRequest, Storage_GetQuoteLatestServer) error {
	return status.Errorf(codes.Unimplemented, "method GetQuoteLatest not implemented")
}
func (UnimplementedStorageServer) mustEmbedUnimplementedStorageServer() {}

// UnsafeStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServer will
// result in compilation errors.
type UnsafeStorageServer interface {
	mustEmbedUnimplementedStorageServer()
}

func RegisterStorageServer(s grpc.ServiceRegistrar, srv StorageServer) {
	s.RegisterService(&Storage_ServiceDesc, srv)
}

func _Storage_ArchiveMetadata_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServer).ArchiveMetadata(&storageArchiveMetadataServer{ServerStream: stream})
}

type Storage_ArchiveMetadataServer interface {
	SendAndClose(*ArchiveResponse) error
	Recv() (*Metadata, error)
	grpc.ServerStream
}

type storageArchiveMetadataServer struct {
	grpc.ServerStream
}

func (x *storageArchiveMetadataServer) SendAndClose(m *ArchiveResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storageArchiveMetadataServer) Recv() (*Metadata, error) {
	m := new(Metadata)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Storage_GetStockOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetStockOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storage_GetStockOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetStockOne(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetStockAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServer).GetStockAll(m, &storageGetStockAllServer{ServerStream: stream})
}

type Storage_GetStockAllServer interface {
	Send(*Stock) error
	grpc.ServerStream
}

type storageGetStockAllServer struct {
	grpc.ServerStream
}

func (x *storageGetStockAllServer) Send(m *Stock) error {
	return x.ServerStream.SendMsg(m)
}

func _Storage_GetQuoteLatest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetQuoteLatestRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServer).GetQuoteLatest(m, &storageGetQuoteLatestServer{ServerStream: stream})
}

type Storage_GetQuoteLatestServer interface {
	Send(*Quote) error
	grpc.ServerStream
}

type storageGetQuoteLatestServer struct {
	grpc.ServerStream
}

func (x *storageGetQuoteLatestServer) Send(m *Quote) error {
	return x.ServerStream.SendMsg(m)
}

// Storage_ServiceDesc is the grpc.ServiceDesc for Storage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Storage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStockOne",
			Handler:    _Storage_GetStockOne_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ArchiveMetadata",
			Handler:       _Storage_ArchiveMetadata_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetStockAll",
			Handler:       _Storage_GetStockAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetQuoteLatest",
			Handler:       _Storage_GetQuoteLatest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "storage.proto",
}
