// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.0
// source: storage.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Storage_ArchiveMetadata_FullMethodName = "/storage.Storage/ArchiveMetadata"
	Storage_GetStockFull_FullMethodName    = "/storage.Storage/GetStockFull"
	Storage_GetQuoteLatest_FullMethodName  = "/storage.Storage/GetQuoteLatest"
)

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageClient interface {
	ArchiveMetadata(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*Counter, error)
	GetStockFull(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Storage_GetStockFullClient, error)
	GetQuoteLatest(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (Storage_GetQuoteLatestClient, error)
}

type storageClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageClient(cc grpc.ClientConnInterface) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) ArchiveMetadata(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*Counter, error) {
	out := new(Counter)
	err := c.cc.Invoke(ctx, Storage_ArchiveMetadata_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetStockFull(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Storage_GetStockFullClient, error) {
	stream, err := c.cc.NewStream(ctx, &Storage_ServiceDesc.Streams[0], Storage_GetStockFull_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &storageGetStockFullClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Storage_GetStockFullClient interface {
	Recv() (*Stock, error)
	grpc.ClientStream
}

type storageGetStockFullClient struct {
	grpc.ClientStream
}

func (x *storageGetStockFullClient) Recv() (*Stock, error) {
	m := new(Stock)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageClient) GetQuoteLatest(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (Storage_GetQuoteLatestClient, error) {
	stream, err := c.cc.NewStream(ctx, &Storage_ServiceDesc.Streams[1], Storage_GetQuoteLatest_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &storageGetQuoteLatestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Storage_GetQuoteLatestClient interface {
	Recv() (*Quote, error)
	grpc.ClientStream
}

type storageGetQuoteLatestClient struct {
	grpc.ClientStream
}

func (x *storageGetQuoteLatestClient) Recv() (*Quote, error) {
	m := new(Quote)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StorageServer is the server API for Storage service.
// All implementations must embed UnimplementedStorageServer
// for forward compatibility
type StorageServer interface {
	ArchiveMetadata(context.Context, *wrapperspb.StringValue) (*Counter, error)
	GetStockFull(*emptypb.Empty, Storage_GetStockFullServer) error
	GetQuoteLatest(*QuoteRequest, Storage_GetQuoteLatestServer) error
	mustEmbedUnimplementedStorageServer()
}

// UnimplementedStorageServer must be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (UnimplementedStorageServer) ArchiveMetadata(context.Context, *wrapperspb.StringValue) (*Counter, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveMetadata not implemented")
}
func (UnimplementedStorageServer) GetStockFull(*emptypb.Empty, Storage_GetStockFullServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStockFull not implemented")
}
func (UnimplementedStorageServer) GetQuoteLatest(*QuoteRequest, Storage_GetQuoteLatestServer) error {
	return status.Errorf(codes.Unimplemented, "method GetQuoteLatest not implemented")
}
func (UnimplementedStorageServer) mustEmbedUnimplementedStorageServer() {}

// UnsafeStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServer will
// result in compilation errors.
type UnsafeStorageServer interface {
	mustEmbedUnimplementedStorageServer()
}

func RegisterStorageServer(s grpc.ServiceRegistrar, srv StorageServer) {
	s.RegisterService(&Storage_ServiceDesc, srv)
}

func _Storage_ArchiveMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).ArchiveMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storage_ArchiveMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).ArchiveMetadata(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetStockFull_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServer).GetStockFull(m, &storageGetStockFullServer{stream})
}

type Storage_GetStockFullServer interface {
	Send(*Stock) error
	grpc.ServerStream
}

type storageGetStockFullServer struct {
	grpc.ServerStream
}

func (x *storageGetStockFullServer) Send(m *Stock) error {
	return x.ServerStream.SendMsg(m)
}

func _Storage_GetQuoteLatest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QuoteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServer).GetQuoteLatest(m, &storageGetQuoteLatestServer{stream})
}

type Storage_GetQuoteLatestServer interface {
	Send(*Quote) error
	grpc.ServerStream
}

type storageGetQuoteLatestServer struct {
	grpc.ServerStream
}

func (x *storageGetQuoteLatestServer) Send(m *Quote) error {
	return x.ServerStream.SendMsg(m)
}

// Storage_ServiceDesc is the grpc.ServiceDesc for Storage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Storage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ArchiveMetadata",
			Handler:    _Storage_ArchiveMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStockFull",
			Handler:       _Storage_GetStockFull_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetQuoteLatest",
			Handler:       _Storage_GetQuoteLatest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "storage.proto",
}
