// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: storage.proto

package pb

import (
	entity "github.com/eviltomorrow/king/lib/grpc/pb/entity"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountQuoteRequest_Kind int32

const (
	CountQuoteRequest_Day  CountQuoteRequest_Kind = 0
	CountQuoteRequest_Week CountQuoteRequest_Kind = 1
)

// Enum value maps for CountQuoteRequest_Kind.
var (
	CountQuoteRequest_Kind_name = map[int32]string{
		0: "Day",
		1: "Week",
	}
	CountQuoteRequest_Kind_value = map[string]int32{
		"Day":  0,
		"Week": 1,
	}
)

func (x CountQuoteRequest_Kind) Enum() *CountQuoteRequest_Kind {
	p := new(CountQuoteRequest_Kind)
	*p = x
	return p
}

func (x CountQuoteRequest_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CountQuoteRequest_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_proto_enumTypes[0].Descriptor()
}

func (CountQuoteRequest_Kind) Type() protoreflect.EnumType {
	return &file_storage_proto_enumTypes[0]
}

func (x CountQuoteRequest_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CountQuoteRequest_Kind.Descriptor instead.
func (CountQuoteRequest_Kind) EnumDescriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3, 0}
}

type GetQuoteLatestRequest_Kind int32

const (
	GetQuoteLatestRequest_Day  GetQuoteLatestRequest_Kind = 0
	GetQuoteLatestRequest_Week GetQuoteLatestRequest_Kind = 1
)

// Enum value maps for GetQuoteLatestRequest_Kind.
var (
	GetQuoteLatestRequest_Kind_name = map[int32]string{
		0: "Day",
		1: "Week",
	}
	GetQuoteLatestRequest_Kind_value = map[string]int32{
		"Day":  0,
		"Week": 1,
	}
)

func (x GetQuoteLatestRequest_Kind) Enum() *GetQuoteLatestRequest_Kind {
	p := new(GetQuoteLatestRequest_Kind)
	*p = x
	return p
}

func (x GetQuoteLatestRequest_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetQuoteLatestRequest_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_proto_enumTypes[1].Descriptor()
}

func (GetQuoteLatestRequest_Kind) Type() protoreflect.EnumType {
	return &file_storage_proto_enumTypes[1]
}

func (x GetQuoteLatestRequest_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetQuoteLatestRequest_Kind.Descriptor instead.
func (GetQuoteLatestRequest_Kind) EnumDescriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7, 0}
}

type PushResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Affected      *PushResponse_AffectedCount `protobuf:"bytes,1,opt,name=affected,proto3" json:"affected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *PushResponse) GetAffected() *PushResponse_AffectedCount {
	if x != nil {
		return x.Affected
	}
	return nil
}

type ShowResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Queried       *ShowResponse_QueriedCount `protobuf:"bytes,1,opt,name=queried,proto3" json:"queried,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowResponse) Reset() {
	*x = ShowResponse{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowResponse) ProtoMessage() {}

func (x *ShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowResponse.ProtoReflect.Descriptor instead.
func (*ShowResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ShowResponse) GetQueried() *ShowResponse_QueriedCount {
	if x != nil {
		return x.Queried
	}
	return nil
}

type Stock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Suspend       string                 `protobuf:"bytes,3,opt,name=suspend,proto3" json:"suspend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stock) Reset() {
	*x = Stock{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *Stock) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Stock) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stock) GetSuspend() string {
	if x != nil {
		return x.Suspend
	}
	return ""
}

type CountQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Kind          CountQuoteRequest_Kind `protobuf:"varint,2,opt,name=kind,proto3,enum=storage.CountQuoteRequest_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountQuoteRequest) Reset() {
	*x = CountQuoteRequest{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountQuoteRequest) ProtoMessage() {}

func (x *CountQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountQuoteRequest.ProtoReflect.Descriptor instead.
func (*CountQuoteRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *CountQuoteRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CountQuoteRequest) GetKind() CountQuoteRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return CountQuoteRequest_Day
}

type CountQuoteRepsonse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountQuoteRepsonse) Reset() {
	*x = CountQuoteRepsonse{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountQuoteRepsonse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountQuoteRepsonse) ProtoMessage() {}

func (x *CountQuoteRepsonse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountQuoteRepsonse.ProtoReflect.Descriptor instead.
func (*CountQuoteRepsonse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

func (x *CountQuoteRepsonse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type CountStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suspend       string                 `protobuf:"bytes,1,opt,name=suspend,proto3" json:"suspend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountStockRequest) Reset() {
	*x = CountStockRequest{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountStockRequest) ProtoMessage() {}

func (x *CountStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountStockRequest.ProtoReflect.Descriptor instead.
func (*CountStockRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *CountStockRequest) GetSuspend() string {
	if x != nil {
		return x.Suspend
	}
	return ""
}

type CountStockRepsonse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountStockRepsonse) Reset() {
	*x = CountStockRepsonse{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountStockRepsonse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountStockRepsonse) ProtoMessage() {}

func (x *CountStockRepsonse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountStockRepsonse.ProtoReflect.Descriptor instead.
func (*CountStockRepsonse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

func (x *CountStockRepsonse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetQuoteLatestRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Code          string                     `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Date          string                     `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Limit         int64                      `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Kind          GetQuoteLatestRequest_Kind `protobuf:"varint,4,opt,name=kind,proto3,enum=storage.GetQuoteLatestRequest_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteLatestRequest) Reset() {
	*x = GetQuoteLatestRequest{}
	mi := &file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteLatestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteLatestRequest) ProtoMessage() {}

func (x *GetQuoteLatestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteLatestRequest.ProtoReflect.Descriptor instead.
func (*GetQuoteLatestRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

func (x *GetQuoteLatestRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetQuoteLatestRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetQuoteLatestRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetQuoteLatestRequest) GetKind() GetQuoteLatestRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return GetQuoteLatestRequest_Day
}

type Quote struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Open            float64                `protobuf:"fixed64,2,opt,name=open,proto3" json:"open,omitempty"`
	Close           float64                `protobuf:"fixed64,3,opt,name=close,proto3" json:"close,omitempty"`
	High            float64                `protobuf:"fixed64,4,opt,name=high,proto3" json:"high,omitempty"`
	Low             float64                `protobuf:"fixed64,5,opt,name=low,proto3" json:"low,omitempty"`
	YesterdayClosed float64                `protobuf:"fixed64,6,opt,name=yesterday_closed,json=yesterdayClosed,proto3" json:"yesterday_closed,omitempty"`
	Volume          int64                  `protobuf:"varint,7,opt,name=volume,proto3" json:"volume,omitempty"`
	Account         float64                `protobuf:"fixed64,8,opt,name=account,proto3" json:"account,omitempty"`
	Date            string                 `protobuf:"bytes,9,opt,name=date,proto3" json:"date,omitempty"`
	NumOfYear       int32                  `protobuf:"varint,10,opt,name=num_of_year,json=numOfYear,proto3" json:"num_of_year,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{8}
}

func (x *Quote) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Quote) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Quote) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Quote) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Quote) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Quote) GetYesterdayClosed() float64 {
	if x != nil {
		return x.YesterdayClosed
	}
	return 0
}

func (x *Quote) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Quote) GetAccount() float64 {
	if x != nil {
		return x.Account
	}
	return 0
}

func (x *Quote) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Quote) GetNumOfYear() int32 {
	if x != nil {
		return x.NumOfYear
	}
	return 0
}

type PushResponse_AffectedCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stocks        int64                  `protobuf:"varint,1,opt,name=stocks,proto3" json:"stocks,omitempty"`
	Days          int64                  `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	Weeks         int64                  `protobuf:"varint,3,opt,name=weeks,proto3" json:"weeks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse_AffectedCount) Reset() {
	*x = PushResponse_AffectedCount{}
	mi := &file_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse_AffectedCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse_AffectedCount) ProtoMessage() {}

func (x *PushResponse_AffectedCount) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse_AffectedCount.ProtoReflect.Descriptor instead.
func (*PushResponse_AffectedCount) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PushResponse_AffectedCount) GetStocks() int64 {
	if x != nil {
		return x.Stocks
	}
	return 0
}

func (x *PushResponse_AffectedCount) GetDays() int64 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *PushResponse_AffectedCount) GetWeeks() int64 {
	if x != nil {
		return x.Weeks
	}
	return 0
}

type ShowResponse_QueriedCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int64                  `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	Weeks         int64                  `protobuf:"varint,3,opt,name=weeks,proto3" json:"weeks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowResponse_QueriedCount) Reset() {
	*x = ShowResponse_QueriedCount{}
	mi := &file_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowResponse_QueriedCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowResponse_QueriedCount) ProtoMessage() {}

func (x *ShowResponse_QueriedCount) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowResponse_QueriedCount.ProtoReflect.Descriptor instead.
func (*ShowResponse_QueriedCount) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ShowResponse_QueriedCount) GetDays() int64 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *ShowResponse_QueriedCount) GetWeeks() int64 {
	if x != nil {
		return x.Weeks
	}
	return 0
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\astorage\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x19lib/entity/metadata.proto\"\xa2\x01\n" +
	"\fPushResponse\x12?\n" +
	"\baffected\x18\x01 \x01(\v2#.storage.PushResponse.AffectedCountR\baffected\x1aQ\n" +
	"\rAffectedCount\x12\x16\n" +
	"\x06stocks\x18\x01 \x01(\x03R\x06stocks\x12\x12\n" +
	"\x04days\x18\x02 \x01(\x03R\x04days\x12\x14\n" +
	"\x05weeks\x18\x03 \x01(\x03R\x05weeks\"\x86\x01\n" +
	"\fShowResponse\x12<\n" +
	"\aqueried\x18\x01 \x01(\v2\".storage.ShowResponse.QueriedCountR\aqueried\x1a8\n" +
	"\fQueriedCount\x12\x12\n" +
	"\x04days\x18\x02 \x01(\x03R\x04days\x12\x14\n" +
	"\x05weeks\x18\x03 \x01(\x03R\x05weeks\"I\n" +
	"\x05Stock\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asuspend\x18\x03 \x01(\tR\asuspend\"w\n" +
	"\x11CountQuoteRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x123\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1f.storage.CountQuoteRequest.KindR\x04kind\"\x19\n" +
	"\x04Kind\x12\a\n" +
	"\x03Day\x10\x00\x12\b\n" +
	"\x04Week\x10\x01\"*\n" +
	"\x12CountQuoteRepsonse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\"-\n" +
	"\x11CountStockRequest\x12\x18\n" +
	"\asuspend\x18\x01 \x01(\tR\asuspend\"*\n" +
	"\x12CountStockRepsonse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\"\xa9\x01\n" +
	"\x15GetQuoteLatestRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x127\n" +
	"\x04kind\x18\x04 \x01(\x0e2#.storage.GetQuoteLatestRequest.KindR\x04kind\"\x19\n" +
	"\x04Kind\x12\a\n" +
	"\x03Day\x10\x00\x12\b\n" +
	"\x04Week\x10\x01\"\xfc\x01\n" +
	"\x05Quote\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04open\x18\x02 \x01(\x01R\x04open\x12\x14\n" +
	"\x05close\x18\x03 \x01(\x01R\x05close\x12\x12\n" +
	"\x04high\x18\x04 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x05 \x01(\x01R\x03low\x12)\n" +
	"\x10yesterday_closed\x18\x06 \x01(\x01R\x0fyesterdayClosed\x12\x16\n" +
	"\x06volume\x18\a \x01(\x03R\x06volume\x12\x18\n" +
	"\aaccount\x18\b \x01(\x01R\aaccount\x12\x12\n" +
	"\x04date\x18\t \x01(\tR\x04date\x12\x1e\n" +
	"\vnum_of_year\x18\n" +
	" \x01(\x05R\tnumOfYear2\x85\x03\n" +
	"\aStorage\x122\n" +
	"\fPushMetadata\x12\t.Metadata\x1a\x15.storage.PushResponse(\x01\x12E\n" +
	"\n" +
	"CountStock\x12\x1a.storage.CountStockRequest\x1a\x1b.storage.CountStockRepsonse\x12E\n" +
	"\n" +
	"CountQuote\x12\x1a.storage.CountQuoteRequest\x1a\x1b.storage.CountQuoteRepsonse\x12;\n" +
	"\vGetStockOne\x12\x1c.google.protobuf.StringValue\x1a\x0e.storage.Stock\x127\n" +
	"\vGetStockAll\x12\x16.google.protobuf.Empty\x1a\x0e.storage.Stock0\x01\x12B\n" +
	"\x0eGetQuoteLatest\x12\x1e.storage.GetQuoteLatestRequest\x1a\x0e.storage.Quote0\x01B\aZ\x05./;pbb\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_storage_proto_goTypes = []any{
	(CountQuoteRequest_Kind)(0),        // 0: storage.CountQuoteRequest.Kind
	(GetQuoteLatestRequest_Kind)(0),    // 1: storage.GetQuoteLatestRequest.Kind
	(*PushResponse)(nil),               // 2: storage.PushResponse
	(*ShowResponse)(nil),               // 3: storage.ShowResponse
	(*Stock)(nil),                      // 4: storage.Stock
	(*CountQuoteRequest)(nil),          // 5: storage.CountQuoteRequest
	(*CountQuoteRepsonse)(nil),         // 6: storage.CountQuoteRepsonse
	(*CountStockRequest)(nil),          // 7: storage.CountStockRequest
	(*CountStockRepsonse)(nil),         // 8: storage.CountStockRepsonse
	(*GetQuoteLatestRequest)(nil),      // 9: storage.GetQuoteLatestRequest
	(*Quote)(nil),                      // 10: storage.Quote
	(*PushResponse_AffectedCount)(nil), // 11: storage.PushResponse.AffectedCount
	(*ShowResponse_QueriedCount)(nil),  // 12: storage.ShowResponse.QueriedCount
	(*entity.Metadata)(nil),            // 13: Metadata
	(*wrapperspb.StringValue)(nil),     // 14: google.protobuf.StringValue
	(*emptypb.Empty)(nil),              // 15: google.protobuf.Empty
}
var file_storage_proto_depIdxs = []int32{
	11, // 0: storage.PushResponse.affected:type_name -> storage.PushResponse.AffectedCount
	12, // 1: storage.ShowResponse.queried:type_name -> storage.ShowResponse.QueriedCount
	0,  // 2: storage.CountQuoteRequest.kind:type_name -> storage.CountQuoteRequest.Kind
	1,  // 3: storage.GetQuoteLatestRequest.kind:type_name -> storage.GetQuoteLatestRequest.Kind
	13, // 4: storage.Storage.PushMetadata:input_type -> Metadata
	7,  // 5: storage.Storage.CountStock:input_type -> storage.CountStockRequest
	5,  // 6: storage.Storage.CountQuote:input_type -> storage.CountQuoteRequest
	14, // 7: storage.Storage.GetStockOne:input_type -> google.protobuf.StringValue
	15, // 8: storage.Storage.GetStockAll:input_type -> google.protobuf.Empty
	9,  // 9: storage.Storage.GetQuoteLatest:input_type -> storage.GetQuoteLatestRequest
	2,  // 10: storage.Storage.PushMetadata:output_type -> storage.PushResponse
	8,  // 11: storage.Storage.CountStock:output_type -> storage.CountStockRepsonse
	6,  // 12: storage.Storage.CountQuote:output_type -> storage.CountQuoteRepsonse
	4,  // 13: storage.Storage.GetStockOne:output_type -> storage.Stock
	4,  // 14: storage.Storage.GetStockAll:output_type -> storage.Stock
	10, // 15: storage.Storage.GetQuoteLatest:output_type -> storage.Quote
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		EnumInfos:         file_storage_proto_enumTypes,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
