// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: assets.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item_Type int32

const (
	Item_STOCK Item_Type = 0
	Item_ETF   Item_Type = 1
)

// Enum value maps for Item_Type.
var (
	Item_Type_name = map[int32]string{
		0: "STOCK",
		1: "ETF",
	}
	Item_Type_value = map[string]int32{
		"STOCK": 0,
		"ETF":   1,
	}
)

func (x Item_Type) Enum() *Item_Type {
	p := new(Item_Type)
	*p = x
	return p
}

func (x Item_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Item_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_assets_proto_enumTypes[0].Descriptor()
}

func (Item_Type) Type() protoreflect.EnumType {
	return &file_assets_proto_enumTypes[0]
}

func (x Item_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Item_Type.Descriptor instead.
func (Item_Type) EnumDescriptor() ([]byte, []int) {
	return file_assets_proto_rawDescGZIP(), []int{1, 0}
}

type ItemListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemListResp) Reset() {
	*x = ItemListResp{}
	mi := &file_assets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemListResp) ProtoMessage() {}

func (x *ItemListResp) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemListResp.ProtoReflect.Descriptor instead.
func (*ItemListResp) Descriptor() ([]byte, []int) {
	return file_assets_proto_rawDescGZIP(), []int{0}
}

func (x *ItemListResp) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ItemListResp) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Item struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FundNo           string                 `protobuf:"bytes,2,opt,name=fund_no,json=fundNo,proto3" json:"fund_no,omitempty"`
	Type             Item_Type              `protobuf:"varint,3,opt,name=type,proto3,enum=account.Item_Type" json:"type,omitempty"`
	CashPosition     float64                `protobuf:"fixed64,4,opt,name=cash_position,json=cashPosition,proto3" json:"cash_position,omitempty"`
	Code             string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Name             string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	OpenInterest     int64                  `protobuf:"varint,7,opt,name=open_interest,json=openInterest,proto3" json:"open_interest,omitempty"`
	OpenId           string                 `protobuf:"bytes,8,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	FirstBuyDatetime int64                  `protobuf:"varint,9,opt,name=first_buy_datetime,json=firstBuyDatetime,proto3" json:"first_buy_datetime,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_assets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_assets_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Item) GetFundNo() string {
	if x != nil {
		return x.FundNo
	}
	return ""
}

func (x *Item) GetType() Item_Type {
	if x != nil {
		return x.Type
	}
	return Item_STOCK
}

func (x *Item) GetCashPosition() float64 {
	if x != nil {
		return x.CashPosition
	}
	return 0
}

func (x *Item) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetOpenInterest() int64 {
	if x != nil {
		return x.OpenInterest
	}
	return 0
}

func (x *Item) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *Item) GetFirstBuyDatetime() int64 {
	if x != nil {
		return x.FirstBuyDatetime
	}
	return 0
}

var File_assets_proto protoreflect.FileDescriptor

const file_assets_proto_rawDesc = "" +
	"\n" +
	"\fassets.proto\x12\aaccount\x1a\x1egoogle/protobuf/wrappers.proto\"T\n" +
	"\fItemListResp\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.account.ItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\xb5\x02\n" +
	"\x04Item\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\afund_no\x18\x02 \x01(\tR\x06fundNo\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.account.Item.TypeR\x04type\x12#\n" +
	"\rcash_position\x18\x04 \x01(\x01R\fcashPosition\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12#\n" +
	"\ropen_interest\x18\a \x01(\x03R\fopenInterest\x12\x17\n" +
	"\aopen_id\x18\b \x01(\tR\x06openId\x12,\n" +
	"\x12first_buy_datetime\x18\t \x01(\x03R\x10firstBuyDatetime\"\x1a\n" +
	"\x04Type\x12\t\n" +
	"\x05STOCK\x10\x00\x12\a\n" +
	"\x03ETF\x10\x012M\n" +
	"\x06Assets\x12C\n" +
	"\fListByUserId\x12\x1c.google.protobuf.StringValue\x1a\x15.account.ItemListRespB\aZ\x05./;pbb\x06proto3"

var (
	file_assets_proto_rawDescOnce sync.Once
	file_assets_proto_rawDescData []byte
)

func file_assets_proto_rawDescGZIP() []byte {
	file_assets_proto_rawDescOnce.Do(func() {
		file_assets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assets_proto_rawDesc), len(file_assets_proto_rawDesc)))
	})
	return file_assets_proto_rawDescData
}

var file_assets_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_assets_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_assets_proto_goTypes = []any{
	(Item_Type)(0),                 // 0: account.Item.Type
	(*ItemListResp)(nil),           // 1: account.ItemListResp
	(*Item)(nil),                   // 2: account.Item
	(*wrapperspb.StringValue)(nil), // 3: google.protobuf.StringValue
}
var file_assets_proto_depIdxs = []int32{
	2, // 0: account.ItemListResp.items:type_name -> account.Item
	0, // 1: account.Item.type:type_name -> account.Item.Type
	3, // 2: account.Assets.ListByUserId:input_type -> google.protobuf.StringValue
	1, // 3: account.Assets.ListByUserId:output_type -> account.ItemListResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_assets_proto_init() }
func file_assets_proto_init() {
	if File_assets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assets_proto_rawDesc), len(file_assets_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assets_proto_goTypes,
		DependencyIndexes: file_assets_proto_depIdxs,
		EnumInfos:         file_assets_proto_enumTypes,
		MessageInfos:      file_assets_proto_msgTypes,
	}.Build()
	File_assets_proto = out.File
	file_assets_proto_goTypes = nil
	file_assets_proto_depIdxs = nil
}
