// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: fund.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Fund_InitAccount_FullMethodName = "/account.Fund/InitAccount"
)

// FundClient is the client API for Fund service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FundClient interface {
	InitAccount(ctx context.Context, in *Account, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type fundClient struct {
	cc grpc.ClientConnInterface
}

func NewFundClient(cc grpc.ClientConnInterface) FundClient {
	return &fundClient{cc}
}

func (c *fundClient) InitAccount(ctx context.Context, in *Account, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Fund_InitAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FundServer is the server API for Fund service.
// All implementations must embed UnimplementedFundServer
// for forward compatibility
type FundServer interface {
	InitAccount(context.Context, *Account) (*emptypb.Empty, error)
	mustEmbedUnimplementedFundServer()
}

// UnimplementedFundServer must be embedded to have forward compatible implementations.
type UnimplementedFundServer struct {
}

func (UnimplementedFundServer) InitAccount(context.Context, *Account) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitAccount not implemented")
}
func (UnimplementedFundServer) mustEmbedUnimplementedFundServer() {}

// UnsafeFundServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FundServer will
// result in compilation errors.
type UnsafeFundServer interface {
	mustEmbedUnimplementedFundServer()
}

func RegisterFundServer(s grpc.ServiceRegistrar, srv FundServer) {
	s.RegisterService(&Fund_ServiceDesc, srv)
}

func _Fund_InitAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServer).InitAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fund_InitAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServer).InitAccount(ctx, req.(*Account))
	}
	return interceptor(ctx, in, info, handler)
}

// Fund_ServiceDesc is the grpc.ServiceDesc for Fund service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fund_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account.Fund",
	HandlerType: (*FundServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitAccount",
			Handler:    _Fund_InitAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fund.proto",
}
