// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: fund.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModifyAliasNameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AliasName     string                 `protobuf:"bytes,1,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty"`
	FundNo        string                 `protobuf:"bytes,2,opt,name=fund_no,json=fundNo,proto3" json:"fund_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyAliasNameReq) Reset() {
	*x = ModifyAliasNameReq{}
	mi := &file_fund_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyAliasNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyAliasNameReq) ProtoMessage() {}

func (x *ModifyAliasNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyAliasNameReq.ProtoReflect.Descriptor instead.
func (*ModifyAliasNameReq) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{0}
}

func (x *ModifyAliasNameReq) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

func (x *ModifyAliasNameReq) GetFundNo() string {
	if x != nil {
		return x.FundNo
	}
	return ""
}

type InitAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AliasName     string                 `protobuf:"bytes,1,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OpeningCash   float64                `protobuf:"fixed64,3,opt,name=opening_cash,json=openingCash,proto3" json:"opening_cash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitAccountReq) Reset() {
	*x = InitAccountReq{}
	mi := &file_fund_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitAccountReq) ProtoMessage() {}

func (x *InitAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitAccountReq.ProtoReflect.Descriptor instead.
func (*InitAccountReq) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{1}
}

func (x *InitAccountReq) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

func (x *InitAccountReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InitAccountReq) GetOpeningCash() float64 {
	if x != nil {
		return x.OpeningCash
	}
	return 0
}

type AccountListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountListResp) Reset() {
	*x = AccountListResp{}
	mi := &file_fund_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountListResp) ProtoMessage() {}

func (x *AccountListResp) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountListResp.ProtoReflect.Descriptor instead.
func (*AccountListResp) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{2}
}

func (x *AccountListResp) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *AccountListResp) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Account struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AliasName        string                 `protobuf:"bytes,1,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FundNo           string                 `protobuf:"bytes,3,opt,name=fund_no,json=fundNo,proto3" json:"fund_no,omitempty"`
	OpeningCash      float64                `protobuf:"fixed64,4,opt,name=opening_cash,json=openingCash,proto3" json:"opening_cash,omitempty"`
	EndCash          float64                `protobuf:"fixed64,5,opt,name=end_cash,json=endCash,proto3" json:"end_cash,omitempty"`
	YesterdayEndCash float64                `protobuf:"fixed64,6,opt,name=yesterday_end_cash,json=yesterdayEndCash,proto3" json:"yesterday_end_cash,omitempty"`
	Status           int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	InitDatetime     int64                  `protobuf:"varint,8,opt,name=init_datetime,json=initDatetime,proto3" json:"init_datetime,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_fund_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

func (x *Account) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Account) GetFundNo() string {
	if x != nil {
		return x.FundNo
	}
	return ""
}

func (x *Account) GetOpeningCash() float64 {
	if x != nil {
		return x.OpeningCash
	}
	return 0
}

func (x *Account) GetEndCash() float64 {
	if x != nil {
		return x.EndCash
	}
	return 0
}

func (x *Account) GetYesterdayEndCash() float64 {
	if x != nil {
		return x.YesterdayEndCash
	}
	return 0
}

func (x *Account) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Account) GetInitDatetime() int64 {
	if x != nil {
		return x.InitDatetime
	}
	return 0
}

var File_fund_proto protoreflect.FileDescriptor

const file_fund_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"fund.proto\x12\aaccount\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"L\n" +
	"\x12ModifyAliasNameReq\x12\x1d\n" +
	"\n" +
	"alias_name\x18\x01 \x01(\tR\taliasName\x12\x17\n" +
	"\afund_no\x18\x02 \x01(\tR\x06fundNo\"k\n" +
	"\x0eInitAccountReq\x12\x1d\n" +
	"\n" +
	"alias_name\x18\x01 \x01(\tR\taliasName\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fopening_cash\x18\x03 \x01(\x01R\vopeningCash\"`\n" +
	"\x0fAccountListResp\x12,\n" +
	"\baccounts\x18\x01 \x03(\v2\x10.account.AccountR\baccounts\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\x83\x02\n" +
	"\aAccount\x12\x1d\n" +
	"\n" +
	"alias_name\x18\x01 \x01(\tR\taliasName\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\afund_no\x18\x03 \x01(\tR\x06fundNo\x12!\n" +
	"\fopening_cash\x18\x04 \x01(\x01R\vopeningCash\x12\x19\n" +
	"\bend_cash\x18\x05 \x01(\x01R\aendCash\x12,\n" +
	"\x12yesterday_end_cash\x18\x06 \x01(\x01R\x10yesterdayEndCash\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12#\n" +
	"\rinit_datetime\x18\b \x01(\x03R\finitDatetime2\xa0\x02\n" +
	"\x04Fund\x12H\n" +
	"\x10ReblanceByUserId\x12\x1c.google.protobuf.StringValue\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\vInitAccount\x12\x17.account.InitAccountReq\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\fListByUserId\x12\x1c.google.protobuf.StringValue\x1a\x18.account.AccountListResp\x12F\n" +
	"\x0fModifyAliasName\x12\x1b.account.ModifyAliasNameReq\x1a\x16.google.protobuf.EmptyB\aZ\x05./;pbb\x06proto3"

var (
	file_fund_proto_rawDescOnce sync.Once
	file_fund_proto_rawDescData []byte
)

func file_fund_proto_rawDescGZIP() []byte {
	file_fund_proto_rawDescOnce.Do(func() {
		file_fund_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fund_proto_rawDesc), len(file_fund_proto_rawDesc)))
	})
	return file_fund_proto_rawDescData
}

var file_fund_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fund_proto_goTypes = []any{
	(*ModifyAliasNameReq)(nil),     // 0: account.ModifyAliasNameReq
	(*InitAccountReq)(nil),         // 1: account.InitAccountReq
	(*AccountListResp)(nil),        // 2: account.AccountListResp
	(*Account)(nil),                // 3: account.Account
	(*wrapperspb.StringValue)(nil), // 4: google.protobuf.StringValue
	(*emptypb.Empty)(nil),          // 5: google.protobuf.Empty
}
var file_fund_proto_depIdxs = []int32{
	3, // 0: account.AccountListResp.accounts:type_name -> account.Account
	4, // 1: account.Fund.ReblanceByUserId:input_type -> google.protobuf.StringValue
	1, // 2: account.Fund.InitAccount:input_type -> account.InitAccountReq
	4, // 3: account.Fund.ListByUserId:input_type -> google.protobuf.StringValue
	0, // 4: account.Fund.ModifyAliasName:input_type -> account.ModifyAliasNameReq
	5, // 5: account.Fund.ReblanceByUserId:output_type -> google.protobuf.Empty
	5, // 6: account.Fund.InitAccount:output_type -> google.protobuf.Empty
	2, // 7: account.Fund.ListByUserId:output_type -> account.AccountListResp
	5, // 8: account.Fund.ModifyAliasName:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fund_proto_init() }
func file_fund_proto_init() {
	if File_fund_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fund_proto_rawDesc), len(file_fund_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fund_proto_goTypes,
		DependencyIndexes: file_fund_proto_depIdxs,
		MessageInfos:      file_fund_proto_msgTypes,
	}.Build()
	File_fund_proto = out.File
	file_fund_proto_goTypes = nil
	file_fund_proto_depIdxs = nil
}
