// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: transaction_record.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record_Action int32

const (
	Record_BUY  Record_Action = 0
	Record_SELL Record_Action = 1
)

// Enum value maps for Record_Action.
var (
	Record_Action_name = map[int32]string{
		0: "BUY",
		1: "SELL",
	}
	Record_Action_value = map[string]int32{
		"BUY":  0,
		"SELL": 1,
	}
)

func (x Record_Action) Enum() *Record_Action {
	p := new(Record_Action)
	*p = x
	return p
}

func (x Record_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Record_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_record_proto_enumTypes[0].Descriptor()
}

func (Record_Action) Type() protoreflect.EnumType {
	return &file_transaction_record_proto_enumTypes[0]
}

func (x Record_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Record_Action.Descriptor instead.
func (Record_Action) EnumDescriptor() ([]byte, []int) {
	return file_transaction_record_proto_rawDescGZIP(), []int{2, 0}
}

type Record_AssetsType int32

const (
	Record_STOCK Record_AssetsType = 0
)

// Enum value maps for Record_AssetsType.
var (
	Record_AssetsType_name = map[int32]string{
		0: "STOCK",
	}
	Record_AssetsType_value = map[string]int32{
		"STOCK": 0,
	}
)

func (x Record_AssetsType) Enum() *Record_AssetsType {
	p := new(Record_AssetsType)
	*p = x
	return p
}

func (x Record_AssetsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Record_AssetsType) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_record_proto_enumTypes[1].Descriptor()
}

func (Record_AssetsType) Type() protoreflect.EnumType {
	return &file_transaction_record_proto_enumTypes[1]
}

func (x Record_AssetsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Record_AssetsType.Descriptor instead.
func (Record_AssetsType) EnumDescriptor() ([]byte, []int) {
	return file_transaction_record_proto_rawDescGZIP(), []int{2, 1}
}

type UserFundReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FundNo   string `protobuf:"bytes,2,opt,name=fund_no,json=fundNo,proto3" json:"fund_no,omitempty"`
	PageNo   int64  `protobuf:"varint,3,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	PageSize int64  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *UserFundReq) Reset() {
	*x = UserFundReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserFundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFundReq) ProtoMessage() {}

func (x *UserFundReq) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFundReq.ProtoReflect.Descriptor instead.
func (*UserFundReq) Descriptor() ([]byte, []int) {
	return file_transaction_record_proto_rawDescGZIP(), []int{0}
}

func (x *UserFundReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserFundReq) GetFundNo() string {
	if x != nil {
		return x.FundNo
	}
	return ""
}

func (x *UserFundReq) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *UserFundReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RecordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records    []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	TotalCount int64     `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *RecordResp) Reset() {
	*x = RecordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_record_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResp) ProtoMessage() {}

func (x *RecordResp) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_record_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordResp.ProtoReflect.Descriptor instead.
func (*RecordResp) Descriptor() ([]byte, []int) {
	return file_transaction_record_proto_rawDescGZIP(), []int{1}
}

func (x *RecordResp) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *RecordResp) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId     string            `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FundNo     string            `protobuf:"bytes,3,opt,name=fund_no,json=fundNo,proto3" json:"fund_no,omitempty"`
	Action     Record_Action     `protobuf:"varint,4,opt,name=action,proto3,enum=account.Record_Action" json:"action,omitempty"`
	AssetsType Record_AssetsType `protobuf:"varint,5,opt,name=assets_type,json=assetsType,proto3,enum=account.Record_AssetsType" json:"assets_type,omitempty"`
	AssetsCode string            `protobuf:"bytes,6,opt,name=assets_code,json=assetsCode,proto3" json:"assets_code,omitempty"`
	ClosePrice float64           `protobuf:"fixed64,7,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`
	Volume     int64             `protobuf:"varint,8,opt,name=volume,proto3" json:"volume,omitempty"`
	Datetime   string            `protobuf:"bytes,9,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Fee        []*Fee            `protobuf:"bytes,10,rep,name=fee,proto3" json:"fee,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_record_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_record_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_transaction_record_proto_rawDescGZIP(), []int{2}
}

func (x *Record) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Record) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Record) GetFundNo() string {
	if x != nil {
		return x.FundNo
	}
	return ""
}

func (x *Record) GetAction() Record_Action {
	if x != nil {
		return x.Action
	}
	return Record_BUY
}

func (x *Record) GetAssetsType() Record_AssetsType {
	if x != nil {
		return x.AssetsType
	}
	return Record_STOCK
}

func (x *Record) GetAssetsCode() string {
	if x != nil {
		return x.AssetsCode
	}
	return ""
}

func (x *Record) GetClosePrice() float64 {
	if x != nil {
		return x.ClosePrice
	}
	return 0
}

func (x *Record) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Record) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *Record) GetFee() []*Fee {
	if x != nil {
		return x.Fee
	}
	return nil
}

type Fee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RecordId string  `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Item     string  `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	Money    float64 `protobuf:"fixed64,4,opt,name=money,proto3" json:"money,omitempty"`
}

func (x *Fee) Reset() {
	*x = Fee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_record_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fee) ProtoMessage() {}

func (x *Fee) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_record_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fee.ProtoReflect.Descriptor instead.
func (*Fee) Descriptor() ([]byte, []int) {
	return file_transaction_record_proto_rawDescGZIP(), []int{3}
}

func (x *Fee) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Fee) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *Fee) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *Fee) GetMoney() float64 {
	if x != nil {
		return x.Money
	}
	return 0
}

var File_transaction_record_proto protoreflect.FileDescriptor

var file_transaction_record_proto_rawDesc = []byte{
	0x0a, 0x18, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x46, 0x75, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x66,
	0x75, 0x6e, 0x64, 0x5f, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x75,
	0x6e, 0x64, 0x4e, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x12, 0x1b, 0x0a,
	0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x58, 0x0a, 0x0a, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x29, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x83, 0x03, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x75, 0x6e, 0x64,
	0x5f, 0x6e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x75, 0x6e, 0x64, 0x4e,
	0x6f, 0x12, 0x2e, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x3b, 0x0a, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0a, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x0a, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x46, 0x65, 0x65, 0x52,
	0x03, 0x66, 0x65, 0x65, 0x22, 0x1b, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07,
	0x0a, 0x03, 0x42, 0x55, 0x59, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x45, 0x4c, 0x4c, 0x10,
	0x01, 0x22, 0x17, 0x0a, 0x0a, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x09, 0x0a, 0x05, 0x53, 0x54, 0x4f, 0x43, 0x4b, 0x10, 0x00, 0x22, 0x5c, 0x0a, 0x03, 0x46, 0x65,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x74,
	0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x32, 0x82, 0x01, 0x0a, 0x0b, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x05, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x12, 0x0f, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x1a, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x3b, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x46, 0x75,
	0x6e, 0x64, 0x12, 0x14, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x46, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x42, 0x07, 0x5a,
	0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transaction_record_proto_rawDescOnce sync.Once
	file_transaction_record_proto_rawDescData = file_transaction_record_proto_rawDesc
)

func file_transaction_record_proto_rawDescGZIP() []byte {
	file_transaction_record_proto_rawDescOnce.Do(func() {
		file_transaction_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_transaction_record_proto_rawDescData)
	})
	return file_transaction_record_proto_rawDescData
}

var file_transaction_record_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_transaction_record_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transaction_record_proto_goTypes = []interface{}{
	(Record_Action)(0),             // 0: account.Record.Action
	(Record_AssetsType)(0),         // 1: account.Record.AssetsType
	(*UserFundReq)(nil),            // 2: account.UserFundReq
	(*RecordResp)(nil),             // 3: account.RecordResp
	(*Record)(nil),                 // 4: account.Record
	(*Fee)(nil),                    // 5: account.Fee
	(*wrapperspb.StringValue)(nil), // 6: google.protobuf.StringValue
}
var file_transaction_record_proto_depIdxs = []int32{
	4, // 0: account.RecordResp.records:type_name -> account.Record
	0, // 1: account.Record.action:type_name -> account.Record.Action
	1, // 2: account.Record.assets_type:type_name -> account.Record.AssetsType
	5, // 3: account.Record.fee:type_name -> account.Fee
	4, // 4: account.Transaction.Write:input_type -> account.Record
	2, // 5: account.Transaction.FindByUserFund:input_type -> account.UserFundReq
	6, // 6: account.Transaction.Write:output_type -> google.protobuf.StringValue
	3, // 7: account.Transaction.FindByUserFund:output_type -> account.RecordResp
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_transaction_record_proto_init() }
func file_transaction_record_proto_init() {
	if File_transaction_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transaction_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserFundReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_record_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_record_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_record_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transaction_record_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_record_proto_goTypes,
		DependencyIndexes: file_transaction_record_proto_depIdxs,
		EnumInfos:         file_transaction_record_proto_enumTypes,
		MessageInfos:      file_transaction_record_proto_msgTypes,
	}.Build()
	File_transaction_record_proto = out.File
	file_transaction_record_proto_rawDesc = nil
	file_transaction_record_proto_goTypes = nil
	file_transaction_record_proto_depIdxs = nil
}
