// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: transaction_record.proto

package pb

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// TransactionRecordClient is the client API for TransactionRecord service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionRecordClient interface {
}

type transactionRecordClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionRecordClient(cc grpc.ClientConnInterface) TransactionRecordClient {
	return &transactionRecordClient{cc}
}

// TransactionRecordServer is the server API for TransactionRecord service.
// All implementations must embed UnimplementedTransactionRecordServer
// for forward compatibility
type TransactionRecordServer interface {
	mustEmbedUnimplementedTransactionRecordServer()
}

// UnimplementedTransactionRecordServer must be embedded to have forward compatible implementations.
type UnimplementedTransactionRecordServer struct {
}

func (UnimplementedTransactionRecordServer) mustEmbedUnimplementedTransactionRecordServer() {}

// UnsafeTransactionRecordServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionRecordServer will
// result in compilation errors.
type UnsafeTransactionRecordServer interface {
	mustEmbedUnimplementedTransactionRecordServer()
}

func RegisterTransactionRecordServer(s grpc.ServiceRegistrar, srv TransactionRecordServer) {
	s.RegisterService(&TransactionRecord_ServiceDesc, srv)
}

// TransactionRecord_ServiceDesc is the grpc.ServiceDesc for TransactionRecord service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionRecord_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account.TransactionRecord",
	HandlerType: (*TransactionRecordServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "transaction_record.proto",
}
