// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: transaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Securities_Type int32

const (
	Securities_STOCK Securities_Type = 0
	Securities_ETF   Securities_Type = 1
)

// Enum value maps for Securities_Type.
var (
	Securities_Type_name = map[int32]string{
		0: "STOCK",
		1: "ETF",
	}
	Securities_Type_value = map[string]int32{
		"STOCK": 0,
		"ETF":   1,
	}
)

func (x Securities_Type) Enum() *Securities_Type {
	p := new(Securities_Type)
	*p = x
	return p
}

func (x Securities_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Securities_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_proto_enumTypes[0].Descriptor()
}

func (Securities_Type) Type() protoreflect.EnumType {
	return &file_transaction_proto_enumTypes[0]
}

func (x Securities_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Securities_Type.Descriptor instead.
func (Securities_Type) EnumDescriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 0}
}

type Securities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FundNo        string                 `protobuf:"bytes,2,opt,name=fund_no,json=fundNo,proto3" json:"fund_no,omitempty"`
	Type          Securities_Type        `protobuf:"varint,3,opt,name=type,proto3,enum=account.Securities_Type" json:"type,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Volume        int64                  `protobuf:"varint,5,opt,name=volume,proto3" json:"volume,omitempty"`
	ClosePrice    float64                `protobuf:"fixed64,6,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Securities) Reset() {
	*x = Securities{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Securities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Securities) ProtoMessage() {}

func (x *Securities) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Securities.ProtoReflect.Descriptor instead.
func (*Securities) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Securities) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Securities) GetFundNo() string {
	if x != nil {
		return x.FundNo
	}
	return ""
}

func (x *Securities) GetType() Securities_Type {
	if x != nil {
		return x.Type
	}
	return Securities_STOCK
}

func (x *Securities) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Securities) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Securities) GetClosePrice() float64 {
	if x != nil {
		return x.ClosePrice
	}
	return 0
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\aaccount\x1a\x1egoogle/protobuf/wrappers.proto\"\xd5\x01\n" +
	"\n" +
	"Securities\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\afund_no\x18\x02 \x01(\tR\x06fundNo\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.account.Securities.TypeR\x04type\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x03R\x06volume\x12\x1f\n" +
	"\vclose_price\x18\x06 \x01(\x01R\n" +
	"closePrice\"\x1a\n" +
	"\x04Type\x12\t\n" +
	"\x05STOCK\x10\x00\x12\a\n" +
	"\x03ETF\x10\x012\x82\x01\n" +
	"\vTransaction\x129\n" +
	"\x04Sell\x12\x13.account.Securities\x1a\x1c.google.protobuf.StringValue\x128\n" +
	"\x03Buy\x12\x13.account.Securities\x1a\x1c.google.protobuf.StringValueB\aZ\x05./;pbb\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transaction_proto_goTypes = []any{
	(Securities_Type)(0),           // 0: account.Securities.Type
	(*Securities)(nil),             // 1: account.Securities
	(*wrapperspb.StringValue)(nil), // 2: google.protobuf.StringValue
}
var file_transaction_proto_depIdxs = []int32{
	0, // 0: account.Securities.type:type_name -> account.Securities.Type
	1, // 1: account.Transaction.Sell:input_type -> account.Securities
	1, // 2: account.Transaction.Buy:input_type -> account.Securities
	2, // 3: account.Transaction.Sell:output_type -> google.protobuf.StringValue
	2, // 4: account.Transaction.Buy:output_type -> google.protobuf.StringValue
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		EnumInfos:         file_transaction_proto_enumTypes,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
