// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: passport.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BindThirdPartyAccountReq_Type int32

const (
	BindThirdPartyAccountReq_EMAIL BindThirdPartyAccountReq_Type = 0
	BindThirdPartyAccountReq_PHONE BindThirdPartyAccountReq_Type = 1
)

// Enum value maps for BindThirdPartyAccountReq_Type.
var (
	BindThirdPartyAccountReq_Type_name = map[int32]string{
		0: "EMAIL",
		1: "PHONE",
	}
	BindThirdPartyAccountReq_Type_value = map[string]int32{
		"EMAIL": 0,
		"PHONE": 1,
	}
)

func (x BindThirdPartyAccountReq_Type) Enum() *BindThirdPartyAccountReq_Type {
	p := new(BindThirdPartyAccountReq_Type)
	*p = x
	return p
}

func (x BindThirdPartyAccountReq_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BindThirdPartyAccountReq_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_passport_proto_enumTypes[0].Descriptor()
}

func (BindThirdPartyAccountReq_Type) Type() protoreflect.EnumType {
	return &file_passport_proto_enumTypes[0]
}

func (x BindThirdPartyAccountReq_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BindThirdPartyAccountReq_Type.Descriptor instead.
func (BindThirdPartyAccountReq_Type) EnumDescriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{5, 0}
}

type AuthReq_Method int32

const (
	AuthReq_PASSWORD AuthReq_Method = 0
	AuthReq_SMS      AuthReq_Method = 1
)

// Enum value maps for AuthReq_Method.
var (
	AuthReq_Method_name = map[int32]string{
		0: "PASSWORD",
		1: "SMS",
	}
	AuthReq_Method_value = map[string]int32{
		"PASSWORD": 0,
		"SMS":      1,
	}
)

func (x AuthReq_Method) Enum() *AuthReq_Method {
	p := new(AuthReq_Method)
	*p = x
	return p
}

func (x AuthReq_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthReq_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_passport_proto_enumTypes[1].Descriptor()
}

func (AuthReq_Method) Type() protoreflect.EnumType {
	return &file_passport_proto_enumTypes[1]
}

func (x AuthReq_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthReq_Method.Descriptor instead.
func (AuthReq_Method) EnumDescriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{7, 0}
}

type CreateVerificationCodeReq_Type int32

const (
	CreateVerificationCodeReq_EMAIL CreateVerificationCodeReq_Type = 0
	CreateVerificationCodeReq_PHONE CreateVerificationCodeReq_Type = 1
)

// Enum value maps for CreateVerificationCodeReq_Type.
var (
	CreateVerificationCodeReq_Type_name = map[int32]string{
		0: "EMAIL",
		1: "PHONE",
	}
	CreateVerificationCodeReq_Type_value = map[string]int32{
		"EMAIL": 0,
		"PHONE": 1,
	}
)

func (x CreateVerificationCodeReq_Type) Enum() *CreateVerificationCodeReq_Type {
	p := new(CreateVerificationCodeReq_Type)
	*p = x
	return p
}

func (x CreateVerificationCodeReq_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateVerificationCodeReq_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_passport_proto_enumTypes[2].Descriptor()
}

func (CreateVerificationCodeReq_Type) Type() protoreflect.EnumType {
	return &file_passport_proto_enumTypes[2]
}

func (x CreateVerificationCodeReq_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateVerificationCodeReq_Type.Descriptor instead.
func (CreateVerificationCodeReq_Type) EnumDescriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{8, 0}
}

type UserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNo        int64                  `protobuf:"varint,1,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReq) Reset() {
	*x = UserReq{}
	mi := &file_passport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReq) ProtoMessage() {}

func (x *UserReq) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReq.ProtoReflect.Descriptor instead.
func (*UserReq) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{0}
}

func (x *UserReq) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *UserReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResp) Reset() {
	*x = UserResp{}
	mi := &file_passport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResp) ProtoMessage() {}

func (x *UserResp) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResp.ProtoReflect.Descriptor instead.
func (*UserResp) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{1}
}

func (x *UserResp) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UserResp) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_passport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{2}
}

func (x *Token) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Token) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *Token) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *Token) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type User struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Account          string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Code             string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Email            string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone            string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Status           int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	RegisterDatetime int64                  `protobuf:"varint,7,opt,name=register_datetime,json=registerDatetime,proto3" json:"register_datetime,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_passport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *User) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User) GetRegisterDatetime() int64 {
	if x != nil {
		return x.RegisterDatetime
	}
	return 0
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_passport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type BindThirdPartyAccountReq struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Type          BindThirdPartyAccountReq_Type `protobuf:"varint,1,opt,name=type,proto3,enum=auth.BindThirdPartyAccountReq_Type" json:"type,omitempty"`
	Id            string                        `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Account       string                        `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindThirdPartyAccountReq) Reset() {
	*x = BindThirdPartyAccountReq{}
	mi := &file_passport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindThirdPartyAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindThirdPartyAccountReq) ProtoMessage() {}

func (x *BindThirdPartyAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindThirdPartyAccountReq.ProtoReflect.Descriptor instead.
func (*BindThirdPartyAccountReq) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{5}
}

func (x *BindThirdPartyAccountReq) GetType() BindThirdPartyAccountReq_Type {
	if x != nil {
		return x.Type
	}
	return BindThirdPartyAccountReq_EMAIL
}

func (x *BindThirdPartyAccountReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BindThirdPartyAccountReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type ConfirmCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BindRequestId string                 `protobuf:"bytes,1,opt,name=bind_request_id,json=bindRequestId,proto3" json:"bind_request_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmCodeReq) Reset() {
	*x = ConfirmCodeReq{}
	mi := &file_passport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmCodeReq) ProtoMessage() {}

func (x *ConfirmCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmCodeReq.ProtoReflect.Descriptor instead.
func (*ConfirmCodeReq) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmCodeReq) GetBindRequestId() string {
	if x != nil {
		return x.BindRequestId
	}
	return ""
}

func (x *ConfirmCodeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type AuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        AuthReq_Method         `protobuf:"varint,1,opt,name=method,proto3,enum=auth.AuthReq_Method" json:"method,omitempty"`
	Credential    *AuthReq_Credential    `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	mi := &file_passport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{7}
}

func (x *AuthReq) GetMethod() AuthReq_Method {
	if x != nil {
		return x.Method
	}
	return AuthReq_PASSWORD
}

func (x *AuthReq) GetCredential() *AuthReq_Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type CreateVerificationCodeReq struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Type          CreateVerificationCodeReq_Type `protobuf:"varint,1,opt,name=type,proto3,enum=auth.CreateVerificationCodeReq_Type" json:"type,omitempty"`
	Account       string                         `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVerificationCodeReq) Reset() {
	*x = CreateVerificationCodeReq{}
	mi := &file_passport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVerificationCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVerificationCodeReq) ProtoMessage() {}

func (x *CreateVerificationCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVerificationCodeReq.ProtoReflect.Descriptor instead.
func (*CreateVerificationCodeReq) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{8}
}

func (x *CreateVerificationCodeReq) GetType() CreateVerificationCodeReq_Type {
	if x != nil {
		return x.Type
	}
	return CreateVerificationCodeReq_EMAIL
}

func (x *CreateVerificationCodeReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type CreateVerificationCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVerificationCodeResp) Reset() {
	*x = CreateVerificationCodeResp{}
	mi := &file_passport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVerificationCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVerificationCodeResp) ProtoMessage() {}

func (x *CreateVerificationCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVerificationCodeResp.ProtoReflect.Descriptor instead.
func (*CreateVerificationCodeResp) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{9}
}

func (x *CreateVerificationCodeResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateVerificationCodeResp) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type ModifyPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyPasswordReq) Reset() {
	*x = ModifyPasswordReq{}
	mi := &file_passport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyPasswordReq) ProtoMessage() {}

func (x *ModifyPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyPasswordReq.ProtoReflect.Descriptor instead.
func (*ModifyPasswordReq) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{10}
}

func (x *ModifyPasswordReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModifyPasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthReq_Credential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReq_Credential) Reset() {
	*x = AuthReq_Credential{}
	mi := &file_passport_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReq_Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq_Credential) ProtoMessage() {}

func (x *AuthReq_Credential) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq_Credential.ProtoReflect.Descriptor instead.
func (*AuthReq_Credential) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{7, 0}
}

func (x *AuthReq_Credential) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AuthReq_Credential) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_passport_proto protoreflect.FileDescriptor

const file_passport_proto_rawDesc = "" +
	"\n" +
	"\x0epassport.proto\x12\x04auth\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"?\n" +
	"\aUserReq\x12\x17\n" +
	"\apage_no\x18\x01 \x01(\x03R\x06pageNo\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\"M\n" +
	"\bUserResp\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".auth.UserR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\x8d\x01\n" +
	"\x05Token\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x03R\texpiresIn\"\xb5\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12+\n" +
	"\x11register_datetime\x18\a \x01(\x03R\x10registerDatetime\"C\n" +
	"\vRegisterReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x9b\x01\n" +
	"\x18BindThirdPartyAccountReq\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.auth.BindThirdPartyAccountReq.TypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\"\x1c\n" +
	"\x04Type\x12\t\n" +
	"\x05EMAIL\x10\x00\x12\t\n" +
	"\x05PHONE\x10\x01\"L\n" +
	"\x0eConfirmCodeReq\x12&\n" +
	"\x0fbind_request_id\x18\x01 \x01(\tR\rbindRequestId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\xcc\x01\n" +
	"\aAuthReq\x12,\n" +
	"\x06method\x18\x01 \x01(\x0e2\x14.auth.AuthReq.MethodR\x06method\x128\n" +
	"\n" +
	"credential\x18\x02 \x01(\v2\x18.auth.AuthReq.CredentialR\n" +
	"credential\x1a8\n" +
	"\n" +
	"Credential\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x1f\n" +
	"\x06Method\x12\f\n" +
	"\bPASSWORD\x10\x00\x12\a\n" +
	"\x03SMS\x10\x01\"\x8d\x01\n" +
	"\x19CreateVerificationCodeReq\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.auth.CreateVerificationCodeReq.TypeR\x04type\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\"\x1c\n" +
	"\x04Type\x12\t\n" +
	"\x05EMAIL\x10\x00\x12\t\n" +
	"\x05PHONE\x10\x01\"O\n" +
	"\x1aCreateVerificationCodeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn\"?\n" +
	"\x11ModifyPasswordReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword2\x88\a\n" +
	"\bPassport\x12U\n" +
	"\x15BindThirdPartyAccount\x12\x1e.auth.BindThirdPartyAccountReq\x1a\x1c.google.protobuf.StringValue\x12;\n" +
	"\vConfirmCode\x12\x14.auth.ConfirmCodeReq\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\x16CreateVerificationCode\x12\x1f.auth.CreateVerificationCodeReq\x1a .auth.CreateVerificationCodeResp\x12;\n" +
	"\bRegister\x12\x11.auth.RegisterReq\x1a\x1c.google.protobuf.StringValue\x12\"\n" +
	"\x04Auth\x12\r.auth.AuthReq\x1a\v.auth.Token\x12&\n" +
	"\n" +
	"RenewToken\x12\v.auth.Token\x1a\v.auth.Token\x122\n" +
	"\vVerifyToken\x12\v.auth.Token\x1a\x16.google.protobuf.Empty\x122\n" +
	"\vRevokeToken\x12\v.auth.Token\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\x05Exist\x12\x1c.google.protobuf.StringValue\x1a\x1a.google.protobuf.BoolValue\x12<\n" +
	"\x04Lock\x12\x1c.google.protobuf.StringValue\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\x06Unlock\x12\x1c.google.protobuf.StringValue\x1a\x16.google.protobuf.Empty\x12%\n" +
	"\x04List\x12\r.auth.UserReq\x1a\x0e.auth.UserResp\x12/\n" +
	"\x03Get\x12\x1c.google.protobuf.StringValue\x1a\n" +
	".auth.User\x12>\n" +
	"\x06Remove\x12\x1c.google.protobuf.StringValue\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\x0eModifyPassword\x12\x17.auth.ModifyPasswordReq\x1a\x16.google.protobuf.EmptyB\aZ\x05./;pbb\x06proto3"

var (
	file_passport_proto_rawDescOnce sync.Once
	file_passport_proto_rawDescData []byte
)

func file_passport_proto_rawDescGZIP() []byte {
	file_passport_proto_rawDescOnce.Do(func() {
		file_passport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_passport_proto_rawDesc), len(file_passport_proto_rawDesc)))
	})
	return file_passport_proto_rawDescData
}

var file_passport_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_passport_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_passport_proto_goTypes = []any{
	(BindThirdPartyAccountReq_Type)(0),  // 0: auth.BindThirdPartyAccountReq.Type
	(AuthReq_Method)(0),                 // 1: auth.AuthReq.Method
	(CreateVerificationCodeReq_Type)(0), // 2: auth.CreateVerificationCodeReq.Type
	(*UserReq)(nil),                     // 3: auth.UserReq
	(*UserResp)(nil),                    // 4: auth.UserResp
	(*Token)(nil),                       // 5: auth.Token
	(*User)(nil),                        // 6: auth.User
	(*RegisterReq)(nil),                 // 7: auth.RegisterReq
	(*BindThirdPartyAccountReq)(nil),    // 8: auth.BindThirdPartyAccountReq
	(*ConfirmCodeReq)(nil),              // 9: auth.ConfirmCodeReq
	(*AuthReq)(nil),                     // 10: auth.AuthReq
	(*CreateVerificationCodeReq)(nil),   // 11: auth.CreateVerificationCodeReq
	(*CreateVerificationCodeResp)(nil),  // 12: auth.CreateVerificationCodeResp
	(*ModifyPasswordReq)(nil),           // 13: auth.ModifyPasswordReq
	(*AuthReq_Credential)(nil),          // 14: auth.AuthReq.Credential
	(*wrapperspb.StringValue)(nil),      // 15: google.protobuf.StringValue
	(*emptypb.Empty)(nil),               // 16: google.protobuf.Empty
	(*wrapperspb.BoolValue)(nil),        // 17: google.protobuf.BoolValue
}
var file_passport_proto_depIdxs = []int32{
	6,  // 0: auth.UserResp.users:type_name -> auth.User
	0,  // 1: auth.BindThirdPartyAccountReq.type:type_name -> auth.BindThirdPartyAccountReq.Type
	1,  // 2: auth.AuthReq.method:type_name -> auth.AuthReq.Method
	14, // 3: auth.AuthReq.credential:type_name -> auth.AuthReq.Credential
	2,  // 4: auth.CreateVerificationCodeReq.type:type_name -> auth.CreateVerificationCodeReq.Type
	8,  // 5: auth.Passport.BindThirdPartyAccount:input_type -> auth.BindThirdPartyAccountReq
	9,  // 6: auth.Passport.ConfirmCode:input_type -> auth.ConfirmCodeReq
	11, // 7: auth.Passport.CreateVerificationCode:input_type -> auth.CreateVerificationCodeReq
	7,  // 8: auth.Passport.Register:input_type -> auth.RegisterReq
	10, // 9: auth.Passport.Auth:input_type -> auth.AuthReq
	5,  // 10: auth.Passport.RenewToken:input_type -> auth.Token
	5,  // 11: auth.Passport.VerifyToken:input_type -> auth.Token
	5,  // 12: auth.Passport.RevokeToken:input_type -> auth.Token
	15, // 13: auth.Passport.Exist:input_type -> google.protobuf.StringValue
	15, // 14: auth.Passport.Lock:input_type -> google.protobuf.StringValue
	15, // 15: auth.Passport.Unlock:input_type -> google.protobuf.StringValue
	3,  // 16: auth.Passport.List:input_type -> auth.UserReq
	15, // 17: auth.Passport.Get:input_type -> google.protobuf.StringValue
	15, // 18: auth.Passport.Remove:input_type -> google.protobuf.StringValue
	13, // 19: auth.Passport.ModifyPassword:input_type -> auth.ModifyPasswordReq
	15, // 20: auth.Passport.BindThirdPartyAccount:output_type -> google.protobuf.StringValue
	16, // 21: auth.Passport.ConfirmCode:output_type -> google.protobuf.Empty
	12, // 22: auth.Passport.CreateVerificationCode:output_type -> auth.CreateVerificationCodeResp
	15, // 23: auth.Passport.Register:output_type -> google.protobuf.StringValue
	5,  // 24: auth.Passport.Auth:output_type -> auth.Token
	5,  // 25: auth.Passport.RenewToken:output_type -> auth.Token
	16, // 26: auth.Passport.VerifyToken:output_type -> google.protobuf.Empty
	16, // 27: auth.Passport.RevokeToken:output_type -> google.protobuf.Empty
	17, // 28: auth.Passport.Exist:output_type -> google.protobuf.BoolValue
	16, // 29: auth.Passport.Lock:output_type -> google.protobuf.Empty
	16, // 30: auth.Passport.Unlock:output_type -> google.protobuf.Empty
	4,  // 31: auth.Passport.List:output_type -> auth.UserResp
	6,  // 32: auth.Passport.Get:output_type -> auth.User
	16, // 33: auth.Passport.Remove:output_type -> google.protobuf.Empty
	16, // 34: auth.Passport.ModifyPassword:output_type -> google.protobuf.Empty
	20, // [20:35] is the sub-list for method output_type
	5,  // [5:20] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_passport_proto_init() }
func file_passport_proto_init() {
	if File_passport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_passport_proto_rawDesc), len(file_passport_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_passport_proto_goTypes,
		DependencyIndexes: file_passport_proto_depIdxs,
		EnumInfos:         file_passport_proto_enumTypes,
		MessageInfos:      file_passport_proto_msgTypes,
	}.Build()
	File_passport_proto = out.File
	file_passport_proto_goTypes = nil
	file_passport_proto_depIdxs = nil
}
