[grpc]
access_ip = ""
bind_ip = "0.0.0.0"
bind_port = 50003

[mongodb]
dsn = "mongodb://admin:admin123@mongo:27017/transaction_db"

[etcd]
endpoints = ["etcd:2379"]

[otel]
dsn = "otel-collector:4317"

[log]
level = "info"

[collector]
code_list = [
    "bj920118",
    "bj920099",
    "bj920016",
    "bj920008",
    "bj920002",
    "bj873***",
    "bj872***",
    "bj871***",
    "bj83****",
    "sh689009",
    "sh688***",
    "sh605***",
    "sh603***",
    "sh601***",
    "sh600***",
    "sz301***",
    "sz300***",
    "sz003816",
    "sz0030**",
    "sz002***",
    "sz001***",
    "sz000***",

	"sh000001",
	"sz399001",
	"sz399006",
	"sh000688",
	"bj899050",
]
source = "sina"
random_period = [5,25] # unit: s
