// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: scheduler.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallbackRequest_StatusCode int32

const (
	CallbackRequest_SUCCESS CallbackRequest_StatusCode = 0
	CallbackRequest_FAILURE CallbackRequest_StatusCode = 1
)

// Enum value maps for CallbackRequest_StatusCode.
var (
	CallbackRequest_StatusCode_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
	}
	CallbackRequest_StatusCode_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
	}
)

func (x CallbackRequest_StatusCode) Enum() *CallbackRequest_StatusCode {
	p := new(CallbackRequest_StatusCode)
	*p = x
	return p
}

func (x CallbackRequest_StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallbackRequest_StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduler_proto_enumTypes[0].Descriptor()
}

func (CallbackRequest_StatusCode) Type() protoreflect.EnumType {
	return &file_scheduler_proto_enumTypes[0]
}

func (x CallbackRequest_StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallbackRequest_StatusCode.Descriptor instead.
func (CallbackRequest_StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0, 0}
}

type CallbackRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	SchedulerId   string                     `protobuf:"bytes,1,opt,name=scheduler_id,json=schedulerId,proto3" json:"scheduler_id,omitempty"`
	Code          CallbackRequest_StatusCode `protobuf:"varint,2,opt,name=code,proto3,enum=cron.CallbackRequest_StatusCode" json:"code,omitempty"`
	ErrorMsg      string                     `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackRequest) Reset() {
	*x = CallbackRequest{}
	mi := &file_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackRequest) ProtoMessage() {}

func (x *CallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackRequest.ProtoReflect.Descriptor instead.
func (*CallbackRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *CallbackRequest) GetSchedulerId() string {
	if x != nil {
		return x.SchedulerId
	}
	return ""
}

func (x *CallbackRequest) GetCode() CallbackRequest_StatusCode {
	if x != nil {
		return x.Code
	}
	return CallbackRequest_SUCCESS
}

func (x *CallbackRequest) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type CallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackResponse) Reset() {
	*x = CallbackResponse{}
	mi := &file_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackResponse) ProtoMessage() {}

func (x *CallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackResponse.ProtoReflect.Descriptor instead.
func (*CallbackResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{1}
}

var File_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x0fscheduler.proto\x12\x04cron\"\xaf\x01\n" +
	"\x0fCallbackRequest\x12!\n" +
	"\fscheduler_id\x18\x01 \x01(\tR\vschedulerId\x124\n" +
	"\x04code\x18\x02 \x01(\x0e2 .cron.CallbackRequest.StatusCodeR\x04code\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\"&\n" +
	"\n" +
	"StatusCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\v\n" +
	"\aFAILURE\x10\x01\"\x12\n" +
	"\x10CallbackResponse2F\n" +
	"\tScheduler\x129\n" +
	"\bCallback\x12\x15.cron.CallbackRequest\x1a\x16.cron.CallbackResponseB\aZ\x05./;pbb\x06proto3"

var (
	file_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_proto_rawDescData []byte
)

func file_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)))
	})
	return file_scheduler_proto_rawDescData
}

var file_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scheduler_proto_goTypes = []any{
	(CallbackRequest_StatusCode)(0), // 0: cron.CallbackRequest.StatusCode
	(*CallbackRequest)(nil),         // 1: cron.CallbackRequest
	(*CallbackResponse)(nil),        // 2: cron.CallbackResponse
}
var file_scheduler_proto_depIdxs = []int32{
	0, // 0: cron.CallbackRequest.code:type_name -> cron.CallbackRequest.StatusCode
	1, // 1: cron.Scheduler.Callback:input_type -> cron.CallbackRequest
	2, // 2: cron.Scheduler.Callback:output_type -> cron.CallbackResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scheduler_proto_init() }
func file_scheduler_proto_init() {
	if File_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_proto_depIdxs,
		EnumInfos:         file_scheduler_proto_enumTypes,
		MessageInfos:      file_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_proto = out.File
	file_scheduler_proto_goTypes = nil
	file_scheduler_proto_depIdxs = nil
}
