[grpc]
access_ip = ""
bind_ip = "0.0.0.0"
bind_port = 50004

[etcd]
endpoints = ["etcd:2379"]

[otel]
dsn = "otel-collector:4317"

[log]
level = "info"

[mysql]
dsn = "admin:admin123@tcp(mysql:3306)/king_cron?charset=utf8mb4&parseTime=true&loc=Local"

[crons]
    [crons.1]
    crontab = "25 18 * * MON,TUE,WED,THU,FRI"
    plan = "CronWithCrawlMetadata"
    
    [crons.2]
    crontab = "0/5 21-23 * * MON,TUE,WED,THU,FRI"
    plan = "CronWithStoreMetadata"