[server]
    host = "0.0.0.0"
    port = 5277

[etcd]
    endpoints = [
        "etcd:2379",
    ]

[otel]
    dsn = "otel-collector:4317"

[redis]
    dsn = "redis://:admin123@redis:6379/0?protocol=3"