package setting

import "time"

const (
	DEFUALT_HANDLE_10TIMEOUT    = 10 * time.Second
	DEFUALT_HANDLE_30TIMEOUT    = 30 * time.Second
	BATCH_HANDLE_LIMIT          = 50
	DB_QUERY_LIMIT              = 50
	GRPC_UNARY_TIMEOUT_10SECOND = DEFUALT_HANDLE_10TIMEOUT
	GRPC_UNARY_TIMEOUT_30SECOND = DEFUALT_HANDLE_30TIMEOUT
	GRPC_UNARY_TIMEOUT_60SECOND = 60 * time.Second
)
