// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: metadata.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Source          string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Code            string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Open            float64                `protobuf:"fixed64,4,opt,name=open,proto3" json:"open,omitempty"`
	YesterdayClosed float64                `protobuf:"fixed64,5,opt,name=yesterday_closed,json=yesterdayClosed,proto3" json:"yesterday_closed,omitempty"`
	Latest          float64                `protobuf:"fixed64,6,opt,name=latest,proto3" json:"latest,omitempty"`
	High            float64                `protobuf:"fixed64,7,opt,name=high,proto3" json:"high,omitempty"`
	Low             float64                `protobuf:"fixed64,8,opt,name=low,proto3" json:"low,omitempty"`
	Volume          int64                  `protobuf:"varint,9,opt,name=volume,proto3" json:"volume,omitempty"`
	Account         float64                `protobuf:"fixed64,10,opt,name=account,proto3" json:"account,omitempty"`
	Date            string                 `protobuf:"bytes,11,opt,name=date,proto3" json:"date,omitempty"`
	Time            string                 `protobuf:"bytes,12,opt,name=time,proto3" json:"time,omitempty"`
	Suspend         string                 `protobuf:"bytes,13,opt,name=suspend,proto3" json:"suspend,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Metadata) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Metadata) GetYesterdayClosed() float64 {
	if x != nil {
		return x.YesterdayClosed
	}
	return 0
}

func (x *Metadata) GetLatest() float64 {
	if x != nil {
		return x.Latest
	}
	return 0
}

func (x *Metadata) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Metadata) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Metadata) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Metadata) GetAccount() float64 {
	if x != nil {
		return x.Account
	}
	return 0
}

func (x *Metadata) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Metadata) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Metadata) GetSuspend() string {
	if x != nil {
		return x.Suspend
	}
	return ""
}

var File_metadata_proto protoreflect.FileDescriptor

const file_metadata_proto_rawDesc = "" +
	"\n" +
	"\x0emetadata.proto\"\xbb\x02\n" +
	"\bMetadata\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04open\x18\x04 \x01(\x01R\x04open\x12)\n" +
	"\x10yesterday_closed\x18\x05 \x01(\x01R\x0fyesterdayClosed\x12\x16\n" +
	"\x06latest\x18\x06 \x01(\x01R\x06latest\x12\x12\n" +
	"\x04high\x18\a \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\b \x01(\x01R\x03low\x12\x16\n" +
	"\x06volume\x18\t \x01(\x03R\x06volume\x12\x18\n" +
	"\aaccount\x18\n" +
	" \x01(\x01R\aaccount\x12\x12\n" +
	"\x04date\x18\v \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\f \x01(\tR\x04time\x12\x18\n" +
	"\asuspend\x18\r \x01(\tR\asuspendB8Z6github.com/eviltomorrow/king/lib/grpc/pb/entity;entityb\x06proto3"

var (
	file_metadata_proto_rawDescOnce sync.Once
	file_metadata_proto_rawDescData []byte
)

func file_metadata_proto_rawDescGZIP() []byte {
	file_metadata_proto_rawDescOnce.Do(func() {
		file_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)))
	})
	return file_metadata_proto_rawDescData
}

var file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metadata_proto_goTypes = []any{
	(*Metadata)(nil), // 0: Metadata
}
var file_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metadata_proto_init() }
func file_metadata_proto_init() {
	if File_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_proto_depIdxs,
		MessageInfos:      file_metadata_proto_msgTypes,
	}.Build()
	File_metadata_proto = out.File
	file_metadata_proto_goTypes = nil
	file_metadata_proto_depIdxs = nil
}
